# Generated by Django 2.2.1 on 2019-07-19 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190719_1633'),
        ('erp_fibre', '0002_fttsproject_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttsproject',
            name='sites',
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='sites',
            field=models.ManyToManyField(blank=True, to='erp_construction.Project'),
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
