# Generated by Django 2.2.1 on 2019-07-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fibre', '0003_auto_20190719_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttsproject',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='ftthproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
