# Generated by Django 2.2.1 on 2019-06-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rates',
            old_name='casuals_rate',
            new_name='rate',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='engineers_rate',
        ),
        migrations.AddField(
            model_name='casual',
            name='country_code',
            field=models.CharField(default='+254', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineer',
            name='country_code',
            field=models.CharField(default='+254', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rates',
            name='worker_type',
            field=models.CharField(default='Engineer', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='casual',
            name='casual_first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='casual',
            name='casual_last_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='casual',
            name='casual_phone_no',
            field=models.CharField(default='+254700123456', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_phone_no',
            field=models.CharField(default='+254700123457', max_length=100),
            preserve_default=False,
        ),
    ]
