# Generated by Django 2.2.1 on 2019-09-20 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftts', '0002_auto_20190920_1017'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamFTTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Engineer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FTTSProject')),
                ('site_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FttsSite')),
                ('team_member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TeamMemberType')),
            ],
        ),
    ]
