# Generated by Django 2.2.1 on 2019-09-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0002_auto_20190919_1646'),
        ('erp_ftts', '0002_auto_20190919_1646'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamFTTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Engineer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FTTSProject')),
                ('site_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FttsSite')),
                ('team_member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TeamMemberType')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeamFTTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Engineer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject')),
                ('team_member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TeamMemberType')),
            ],
        ),
    ]
