# Generated by Django 2.2.1 on 2019-09-14 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0002_auto_20190914_1202'),
        ('users', '0002_teammembertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTeamFTTH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Engineer')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject')),
                ('team_member_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.TeamMemberType')),
            ],
        ),
    ]
