# Generated by Django 2.2.1 on 2019-06-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190610_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissionmap',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authpermission', to='contenttypes.ContentType', unique=True),
        ),
    ]
