# Generated by Django 2.2.1 on 2019-09-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_projectteamftth_projectteamftts_teammembertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='devid',
            new_name='device',
        ),
    ]
