# Generated by Django 2.2.1 on 2019-05-24 09:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190524_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casual',
            name='casual_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='customuser_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_phone_no',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number', max_length=128, region=None),
        ),
    ]
