# Generated by Django 2.2.1 on 2019-06-13 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_engineer_eng_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='eng_id',
        ),
    ]
