# Generated by Django 2.2.1 on 2019-06-10 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190610_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissionmap',
            old_name='can_create',
            new_name='create',
        ),
        migrations.RenameField(
            model_name='permissionmap',
            old_name='can_edit',
            new_name='edit',
        ),
        migrations.RenameField(
            model_name='permissionmap',
            old_name='can_view',
            new_name='view',
        ),
    ]
