# Generated by Django 2.2.1 on 2019-06-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_engineer_eng_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casual',
            old_name='casual_first_name',
            new_name='casual_name',
        ),
        migrations.RemoveField(
            model_name='casual',
            name='casual_last_name',
        ),
    ]
