# Generated by Django 2.2.1 on 2019-06-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190610_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionmap',
            name='approver',
            field=models.BooleanField(default=False),
        ),
    ]
