# Generated by Django 2.2.1 on 2019-09-06 04:16

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFtthBackfilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/backfilling/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('backfilling_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthCableInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/cableinstallation/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('cableinstallation_date', models.DateField(blank=True, null=True, unique=True)),
                ('cableinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthCoreProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/coreprovision/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('coreprovision_date', models.DateField(blank=True, null=True, unique=True)),
                ('coreprovision_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthOTDRTraces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/OTDRTraces/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('OTDRTraces_date', models.DateField(blank=True, null=True, unique=True)),
                ('OTDRTraces_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthPoleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/poleinstallation/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('poleinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthPowerLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/powerlevels/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('powerlevels_date', models.DateField(blank=True, null=True, unique=True)),
                ('powerlevels_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingEnclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingencore/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('splicingencore_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingencore_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingFAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingFAT/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFAT_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFAT_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingFDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingFDT/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFDT_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFDT_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/trenching/%Y/%m/%d/')),
                ('work_day', models.DateField(blank=True, null=True, unique=True)),
                ('trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthAccessApprovalCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_approval', models.FileField(upload_to='files/CivilWorksTeam/ftth/accessapproval/%Y/%m/%d/')),
                ('access_approval_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthAccessApprovalInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_approval', models.FileField(upload_to='files/InstallationTeamFtth/accessapproval/%Y/%m/%d/')),
                ('access_approval_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthBackfilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_backfilling_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/backfilling/%Y/%m/%d/')),
                ('ftth_backfilling_image_2', models.ImageField(upload_to='images/ftth/CivilWorksTeam/backfilling/%Y/%m/%d/')),
                ('ftth_backfilling_image_3', models.ImageField(upload_to='images/ftth/CivilWorksTeam/backfilling/%Y/%m/%d/')),
                ('ftth_backfilling_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthBackfillingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backfilling_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/backfilling/%Y/%m/%d/')),
                ('backfilling_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCableInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_cable_installation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/cableinstallation/%Y/%m/%d/')),
                ('ftth_cable_installation_image_2', models.ImageField(upload_to='images/ftth/CivilWorksTeam/cableinstallation/%Y/%m/%d/')),
                ('ftth_cable_installation_image_3', models.ImageField(upload_to='images/ftth/CivilWorksTeam/cableinstallation/%Y/%m/%d/')),
                ('ftth_cable_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCableInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cableinstallation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/cableinstallation/%Y/%m/%d/')),
                ('cableinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCertificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_snag_document', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/SafaricomTeamftth/snag/'))),
                ('ftth_snag_document_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftth_crq_ticketno', models.IntegerField(blank=True, null=True)),
                ('ftth_crq_document', models.FileField(blank=True, null=True, upload_to='files/SafaricomTeamftth/crq/%Y/%m/%d/')),
                ('ftth_crq_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftth_final_acceptance_cert', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTSProjects', 'files/SafaricomTeamftth/finalcert/'))),
                ('ftth_final_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftth_operational_acceptance_cert', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTSProjects', 'files/SafaricomTeamftth/opsacceptance/'))),
                ('ftth_operational_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftth_homepass_acceptance_cert', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTSProjects', 'files/SafaricomTeamftth/opsacceptance/'))),
                ('ftth_homepass_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftth_conditional_acceptance_cert', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/SafaricomTeamftth/conditionalcert/'))),
                ('ftth_conditional_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCivilTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_civil_team_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCommercialTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_po', models.FileField(blank=True, null=True, upload_to='files/ftth/CommercialTeam/po/%Y/%m/%d/')),
                ('ftth_po_no', models.IntegerField(blank=True, null=True)),
                ('ftth_po_amount', models.IntegerField(blank=True, null=True)),
                ('ftth_boq', models.FileField(blank=True, null=True, upload_to='files/ftth/CommercialTeam/boq/%Y/%m/%d/')),
                ('ftth_quote', models.FileField(blank=True, null=True, upload_to='files/ftth/CommercialTeam/quote/%Y/%m/%d/')),
                ('ftth_wayleave_application', models.FileField(blank=True, null=True, upload_to='files/ftth/CommercialTeam/wayleaveapplication/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCoreProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_core_provision_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/coreprovision/%Y/%m/%d/')),
                ('ftth_core_provision_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/coreprovision/%Y/%m/%d/')),
                ('ftth_core_provision_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/coreprovision/%Y/%m/%d/')),
                ('ftth_core_provision_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCoreProvisionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coreprovision_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/coreprovision/%Y/%m/%d/')),
                ('coreprovision_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthHealthDocsInstallationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_safety_comm_plan', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/InstallationTeamFtth/projectsafety/'))),
                ('project_safety_comm_plan_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard_analysis_form', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/InstallationTeamFtth/hazardanalysis/'))),
                ('hazard_analysis_form_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_form', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/InstallationTeamFtth/attendanceform/'))),
                ('attendance_form_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_report', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/InstallationTeamFtth/ftth/OHSrtp/'))),
                ('incident_report_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('health_documents_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthHealthDocumentsCivilTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_safety_comm_plan', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/CivilWorksTeam/ftth/projectsafety/'))),
                ('project_safety_comm_plan_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('hazard_analysis_form', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/CivilWorksTeam/ftth/hazardanalysis/'))),
                ('hazard_analysis_form_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('attendance_form', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/CivilWorksTeam/ftth/attendanceform/'))),
                ('attendance_form_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('OHS_risk_treatment_plan', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/CivilWorksTeam/ftth/OHSrtp/'))),
                ('OHS_risk_treatment_plan_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_report', models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTSProjects', 'files/CivilWorksTeam/ftth/OHSrtp/'))),
                ('incident_report_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('health_documents_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthInstallationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_asbuit_received', models.BooleanField(default=False)),
                ('ftth_asbuilt_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('ftth_network_activation', models.BooleanField(default=False)),
                ('ftth_network_activation_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('ftth_installation_team_comment', models.CharField(blank=True, max_length=200, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthInterceptionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interception_point_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_issue', models.CharField(max_length=200)),
                ('ftth_issue_image', models.ImageField(blank=True, null=True, upload_to='images/InstallationTeamFtth/issues/%Y/%m/%d/')),
                ('ftth_issue_sorted_image', models.ImageField(blank=True, null=True, upload_to='images/InstallationTeamFtth/issues/%Y/%m/%d/')),
                ('closed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthOTDRTraces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_otdr_traces_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/OTDRTraces/%Y/%m/%d/')),
                ('ftth_otdr_traces_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/OTDRTraces/%Y/%m/%d/')),
                ('ftth_otdr_traces_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/OTDRTraces/%Y/%m/%d/')),
                ('ftth_otdr_traces_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthOTDRTracesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('OTDRTraces_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/OTDRTraces/%Y/%m/%d/')),
                ('OTDRTraces_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPoleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_pole_installation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
                ('ftth_pole_installation_image_2', models.ImageField(upload_to='images/ftth/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
                ('ftth_pole_installation_image_3', models.ImageField(upload_to='images/ftth/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
                ('ftth_pole_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPoleInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('poleinstallation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
                ('poleinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPoToSupplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_duct', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/poduct/%Y/%m/%d/')),
                ('ftth_cable', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/pocable/%Y/%m/%d/')),
                ('ftth_manholes', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/pomanholes/%Y/%m/%d/')),
                ('ftth_cabinets', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/pocabinets/%Y/%m/%d/')),
                ('ftth_poles', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/popoles/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPowerLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_power_level_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/powerlevels/%Y/%m/%d/')),
                ('ftth_power_level_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/powerlevels/%Y/%m/%d/')),
                ('ftth_power_level_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/powerlevels/%Y/%m/%d/')),
                ('ftth_power_level_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPowerLevelsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('powerlevels_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/powerlevels/%Y/%m/%d/')),
                ('powerlevels_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthProcurementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_bom', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/bom/%Y/%m/%d/')),
                ('ftth_initial_invoice', models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/initialinvoice/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FTTHProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_kmz', models.FileField(blank=True, null=True, upload_to='files/ftth/InitialKMZ/%Y/%m/%d/')),
                ('signed_operation_acceptance', models.BooleanField(blank=True, default=False, null=True)),
                ('ftth_final_acceptance_cert', models.FileField(blank=True, null=True, upload_to='files/ftth/SafaricomTeamftth/finalcert/%Y/%m/%d/')),
                ('ftth_final_acceptance_cert_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_acknowledged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FtthSignalTesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_signal_testing_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ftth_splicing_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingEnclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('splicing_encore_distance', models.FloatField(default=0)),
                ('ftth_splicing_encore_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingenclosure/%Y/%m/%d/')),
                ('ftth_splicing_encore_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingenclosure/%Y/%m/%d/')),
                ('ftth_splicing_encore_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingenclosuresplicingenclosure/%Y/%m/%d/')),
                ('ftth_splicing_encore_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingEnclosureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingencore_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingenclosure/%Y/%m/%d/')),
                ('splicingencore_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_splicing_fat_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFAT/%Y/%m/%d/')),
                ('ftth_splicing_fat_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFAT/%Y/%m/%d/')),
                ('ftth_splicing_fat_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFAT/%Y/%m/%d/')),
                ('ftth_splicing_fat_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFATImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingFAT_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFAT/%Y/%m/%d/')),
                ('splicingFAT_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_splicing_fdt_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFDT/%Y/%m/%d/')),
                ('ftth_splicing_fdt_image_2', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFDT/%Y/%m/%d/')),
                ('ftth_splicing_fdt_image_3', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFDT/%Y/%m/%d/')),
                ('ftth_splicing_fdt_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFDTImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingFDT_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFDT/%Y/%m/%d/')),
                ('splicingFDT_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ftthSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('site_latitude', models.FloatField()),
                ('site_longitude', models.FloatField()),
                ('distance_from_ip', models.FloatField(blank=True, null=True)),
                ('no_of_fdts', models.IntegerField(blank=True, null=True)),
                ('high_level_design', models.FileField(blank=True, null=True, upload_to='files/ftth/survey/highleveldesigns/%Y/%m/%d/')),
                ('ftth_survey_comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ftthSurveyPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('survey_image_1', models.ImageField(upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_image_2', models.ImageField(blank=True, null=True, upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_image_3', models.ImageField(blank=True, null=True, upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_images_comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('ftth_trenching_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('ftth_trenching_image_2', models.ImageField(upload_to='images/ftth/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('ftth_trenching_image_3', models.ImageField(upload_to='images/ftth/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('ftth_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trenching_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('day_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftthtrenchingimages', to='erp_ftth.DailyFtthTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
