# Generated by Django 2.2.1 on 2019-08-22 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_ftth', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftthtrenching',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='ftthtrenching',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthtrenching',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsurveyphotos',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsurveyphotos',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='ftth_interception_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FtthInterceptionPoint'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='survey_photos',
            field=models.ManyToManyField(to='erp_ftth.ftthSurveyPhotos'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfdt',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfdt',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfat',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfat',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicingenclosure',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingenclosure',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_encore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthSplicingEnclosure'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_fat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthSplicingFAT'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_fdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthSplicingFDT'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_core_provision',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthCoreProvision'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_otdr_traces',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthOTDRTraces'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_power_levels',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthPowerLevels'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthpowerlevels',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthpowerlevels',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthotdrtraces',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthotdrtraces',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthissues',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthissues',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthinterceptionpoint',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='ftthinterceptionpoint',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_issues',
            field=models.ManyToManyField(blank=True, to='erp_ftth.FtthIssues'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_signal_testing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthSignalTesting'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_splicing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthSplicing'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcoreprovision',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcoreprovision',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcommercialteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcommercialteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_backfiling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthBackfilling'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_cable_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthCableInstallation'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_pole_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthPoleInstallation'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_trenching',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FtthTrenching'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
    ]
