# Generated by Django 2.2.1 on 2019-08-26 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_ftth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFtthBackfilling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/backfilling/%Y/%m/%d/')),
                ('backfilling_date', models.DateField(blank=True, null=True, unique=True)),
                ('backfilling_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='backfilling', to='erp_ftth.FtthBackfilling')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthCableInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/cableinstallation/%Y/%m/%d/')),
                ('cableinstallation_date', models.DateField(blank=True, null=True, unique=True)),
                ('cableinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cableinstallation', to='erp_ftth.FtthCableInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthCoreProvision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/coreprovision/%Y/%m/%d/')),
                ('coreprovision_date', models.DateField(blank=True, null=True, unique=True)),
                ('coreprovision_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coreprovision', to='erp_ftth.FtthCoreProvision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthOTDRTraces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/OTDRTraces/%Y/%m/%d/')),
                ('OTDRTraces_date', models.DateField(blank=True, null=True, unique=True)),
                ('OTDRTraces_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthPoleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/poleinstallation/%Y/%m/%d/')),
                ('poleinstallation_date', models.DateField(blank=True, null=True, unique=True)),
                ('poleinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='poleinstallation', to='erp_ftth.FtthPoleInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthPowerLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/powerlevels/%Y/%m/%d/')),
                ('powerlevels_date', models.DateField(blank=True, null=True, unique=True)),
                ('powerlevels_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='powerlevels', to='erp_ftth.FtthPowerLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingEnclosure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingencore/%Y/%m/%d/')),
                ('splicingencore_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingencore_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingencore', to='erp_ftth.FtthSplicingEnclosure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingFAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingFAT/%Y/%m/%d/')),
                ('splicingFAT_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFAT_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingFAT', to='erp_ftth.FtthSplicingFAT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthSplicingFDT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/splicingFDT/%Y/%m/%d/')),
                ('splicingFDT_date', models.DateField(blank=True, null=True, unique=True)),
                ('splicingFDT_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingFDT', to='erp_ftth.FtthSplicingFDT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailyFtthTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftth/Casuals/trenching/%Y/%m/%d/')),
                ('trenching_date', models.DateField(blank=True, null=True, unique=True)),
                ('trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trenching', to='erp_ftth.FtthTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='ftthinstallationteam',
            old_name='ftts_asbuilt_comment',
            new_name='ftth_asbuilt_comment',
        ),
        migrations.RenameField(
            model_name='ftthproject',
            old_name='ftts_final_acceptance_cert',
            new_name='ftth_final_acceptance_cert',
        ),
        migrations.RenameField(
            model_name='ftthproject',
            old_name='ftts_final_acceptance_cert_comment',
            new_name='ftth_final_acceptance_cert_comment',
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_network_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_network_activation_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='ftth_budget',
            field=models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/budget/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ftthotdrtraces',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftthprocurementteam',
            name='ftth_bom',
            field=models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/bom/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ftthprocurementteam',
            name='ftth_initial_invoice',
            field=models.FileField(blank=True, null=True, upload_to='files/ftth/ProcurementTeam/initialinvoice/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='FtthTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trenching_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trenchingimage', to='erp_ftth.DailyFtthTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFDTImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingFDT_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFDT/%Y/%m/%d/')),
                ('splicingFDT_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingFDTimage', to='erp_ftth.DailyFtthSplicingFDT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingFATImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingFAT_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingFAT/%Y/%m/%d/')),
                ('splicingFAT_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingFATimage', to='erp_ftth.DailyFtthSplicingFAT')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthSplicingEnclosureImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('splicingencore_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/splicingencore/%Y/%m/%d/')),
                ('splicingencore_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='splicingencoreimage', to='erp_ftth.DailyFtthSplicingEnclosure')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPowerLevelsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('powerlevels_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/powerlevels/%Y/%m/%d/')),
                ('powerlevels_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='powerlevelsimage', to='erp_ftth.DailyFtthPowerLevels')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthPoleInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('poleinstallation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
                ('poleinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='poleinstallationimage', to='erp_ftth.DailyFtthPoleInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthOTDRTracesImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('OTDRTraces_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/OTDRTraces/%Y/%m/%d/')),
                ('OTDRTraces_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OTDRTracesimage', to='erp_ftth.DailyFtthOTDRTraces')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCoreProvisionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('coreprovision_image_1', models.ImageField(upload_to='images/ftth/InstallationTeam/coreprovision/%Y/%m/%d/')),
                ('coreprovision_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='coreprovisionimage', to='erp_ftth.DailyFtthCoreProvision')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthCableInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cableinstallation_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/cableinstallation/%Y/%m/%d/')),
                ('cableinstallation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cableinstallationimage', to='erp_ftth.DailyFtthCableInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FtthBackfillingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('backfilling_image_1', models.ImageField(upload_to='images/ftth/CivilWorksTeam/backfilling/%Y/%m/%d/')),
                ('backfilling_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='backfillingimage', to='erp_ftth.DailyFtthBackfilling')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailyftthotdrtraces',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='OTDRTraces', to='erp_ftth.FtthOTDRTraces'),
        ),
    ]
