# Generated by Django 2.2.1 on 2019-09-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftthproject',
            name='description',
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthproject',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthproject',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ftthsurveyphotos',
            name='work_day',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ftthinterceptionpoint',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftthinterceptionpoint',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftthsurvey',
            name='site_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftthsurvey',
            name='site_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ftthsurvey',
            name='survey_photos',
            field=models.ManyToManyField(blank=True, null=True, to='erp_ftth.ftthSurveyPhotos'),
        ),
    ]
