# Generated by Django 2.2.1 on 2019-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0002_auto_20190917_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftthsurvey',
            name='survey_photos',
            field=models.ManyToManyField(blank=True, to='erp_ftth.ftthSurveyPhotos'),
        ),
    ]
