# Generated by Django 2.2.1 on 2019-09-16 11:54

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0002_auto_20190916_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyftthpoleinstallation',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/poleinstallation/')),
        ),
        migrations.AlterField(
            model_name='dailyftthtrenching',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/trenching/')),
        ),
        migrations.AlterField(
            model_name='ftthcertificates',
            name='ftth_conditional_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/SafaricomTeamftth/conditionalcert/')),
        ),
        migrations.AlterField(
            model_name='ftthcertificates',
            name='ftth_final_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTHProjects', 'files/SafaricomTeamftth/finalcert/')),
        ),
        migrations.AlterField(
            model_name='ftthcertificates',
            name='ftth_homepass_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTHProjects', 'files/SafaricomTeamftth/opsacceptance/')),
        ),
        migrations.AlterField(
            model_name='ftthcertificates',
            name='ftth_operational_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTHProjects', 'files/SafaricomTeamftth/opsacceptance/')),
        ),
        migrations.AlterField(
            model_name='ftthcertificates',
            name='ftth_snag_document',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/SafaricomTeamftth/snag/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocsinstallationteam',
            name='attendance_form',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/InstallationTeamFtth/attendanceform/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocsinstallationteam',
            name='hazard_analysis_form',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/InstallationTeamFtth/hazardanalysis/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocsinstallationteam',
            name='incident_report',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/InstallationTeamFtth/ftth/OHSrtp/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocsinstallationteam',
            name='project_safety_comm_plan',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/InstallationTeamFtth/projectsafety/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocumentscivilteam',
            name='OHS_risk_treatment_plan',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/CivilWorksTeam/ftth/OHSrtp/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocumentscivilteam',
            name='attendance_form',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/CivilWorksTeam/ftth/attendanceform/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocumentscivilteam',
            name='hazard_analysis_form',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/CivilWorksTeam/ftth/hazardanalysis/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocumentscivilteam',
            name='incident_report',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/CivilWorksTeam/ftth/OHSrtp/')),
        ),
        migrations.AlterField(
            model_name='ftthhealthdocumentscivilteam',
            name='project_safety_comm_plan',
            field=models.FileField(upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/CivilWorksTeam/ftth/projectsafety/')),
        ),
        migrations.AlterField(
            model_name='ftthpoleinstallation',
            name='ftth_pole_installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/poleinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthpoleinstallation',
            name='ftth_pole_installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/poleinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthpoleinstallation',
            name='ftth_pole_installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/poleinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthpoleinstallationimage',
            name='poleinstallation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/CivilWorksTeam/poleinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthtrenching',
            name='ftth_trenching_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/trenching/')),
        ),
        migrations.AlterField(
            model_name='ftthtrenching',
            name='ftth_trenching_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/trenching/')),
        ),
        migrations.AlterField(
            model_name='ftthtrenching',
            name='ftth_trenching_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/trenching/')),
        ),
        migrations.AlterField(
            model_name='ftthtrenchingimage',
            name='trenching_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/CivilWorksTeam/trenching/')),
        ),
    ]
