# Generated by Django 2.2.1 on 2019-09-13 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0002_auto_20190911_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftthproject',
            name='ftth_final_acceptance_cert',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='ftth_final_acceptance_cert_comment',
        ),
        migrations.AlterField(
            model_name='ftthcivilteam',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject'),
        ),
        migrations.AlterField(
            model_name='ftthinstallationteam',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject'),
        ),
        migrations.AlterField(
            model_name='ftthprocurementteam',
            name='po_to_supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FtthPoToSupplier'),
        ),
        migrations.AlterField(
            model_name='ftthsignaltesting',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject'),
        ),
        migrations.AlterField(
            model_name='ftthsplicing',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftth.FTTHProject'),
        ),
    ]
