# Generated by Django 2.2.1 on 2019-09-16 13:03

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftth', '0003_auto_20190916_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyftthpowerlevels',
            name='powerlevels_date',
        ),
        migrations.AlterField(
            model_name='dailyftthbackfilling',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/backfilling/')),
        ),
        migrations.AlterField(
            model_name='dailyftthcableinstallation',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/cableinstallation/')),
        ),
        migrations.AlterField(
            model_name='dailyftthcoreprovision',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/coreprovision/')),
        ),
        migrations.AlterField(
            model_name='dailyftthotdrtraces',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/OTDRTraces/')),
        ),
        migrations.AlterField(
            model_name='dailyftthpowerlevels',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'files/ftth/Casuals/powerlevels/')),
        ),
        migrations.AlterField(
            model_name='dailyftthsplicingenclosure',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/splicingencore/')),
        ),
        migrations.AlterField(
            model_name='dailyftthsplicingfat',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/splicingFAT/')),
        ),
        migrations.AlterField(
            model_name='dailyftthsplicingfdt',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('FTTHProjects', 'files/ftth/Casuals/splicingFDT/')),
        ),
        migrations.AlterField(
            model_name='ftthbackfilling',
            name='ftth_backfilling_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/backfilling/')),
        ),
        migrations.AlterField(
            model_name='ftthbackfilling',
            name='ftth_backfilling_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/backfilling/')),
        ),
        migrations.AlterField(
            model_name='ftthbackfilling',
            name='ftth_backfilling_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/backfilling/')),
        ),
        migrations.AlterField(
            model_name='ftthbackfillingimage',
            name='backfilling_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/CivilWorksTeam/backfilling/')),
        ),
        migrations.AlterField(
            model_name='ftthcableinstallation',
            name='ftth_cable_installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/cableinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthcableinstallation',
            name='ftth_cable_installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/cableinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthcableinstallation',
            name='ftth_cable_installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/CivilWorksTeam/cableinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthcableinstallationimage',
            name='cableinstallation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/CivilWorksTeam/cableinstallation/')),
        ),
        migrations.AlterField(
            model_name='ftthcoreprovision',
            name='ftth_core_provision_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/coreprovision/')),
        ),
        migrations.AlterField(
            model_name='ftthcoreprovision',
            name='ftth_core_provision_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/coreprovision/')),
        ),
        migrations.AlterField(
            model_name='ftthcoreprovision',
            name='ftth_core_provision_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/coreprovision/')),
        ),
        migrations.AlterField(
            model_name='ftthcoreprovisionimage',
            name='coreprovision_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/coreprovision/')),
        ),
        migrations.AlterField(
            model_name='ftthotdrtraces',
            name='ftth_otdr_traces_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/OTDRTraces/')),
        ),
        migrations.AlterField(
            model_name='ftthotdrtraces',
            name='ftth_otdr_traces_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/OTDRTraces/')),
        ),
        migrations.AlterField(
            model_name='ftthotdrtraces',
            name='ftth_otdr_traces_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/OTDRTraces/')),
        ),
        migrations.AlterField(
            model_name='ftthotdrtracesimage',
            name='OTDRTraces_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/OTDRTraces/')),
        ),
        migrations.AlterField(
            model_name='ftthpowerlevels',
            name='ftth_power_level_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/powerlevels/')),
        ),
        migrations.AlterField(
            model_name='ftthpowerlevels',
            name='ftth_power_level_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/powerlevels/')),
        ),
        migrations.AlterField(
            model_name='ftthpowerlevels',
            name='ftth_power_level_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/powerlevels/')),
        ),
        migrations.AlterField(
            model_name='ftthpowerlevelsimage',
            name='powerlevels_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/powerlevels/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingenclosure',
            name='ftth_splicing_encore_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingenclosure/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingenclosure',
            name='ftth_splicing_encore_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingenclosure/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingenclosure',
            name='ftth_splicing_encore_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingenclosure/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingenclosureimage',
            name='splicingencore_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/splicingenclosure/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfat',
            name='ftth_splicing_fat_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFAT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfat',
            name='ftth_splicing_fat_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFAT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfat',
            name='ftth_splicing_fat_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFAT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfatimage',
            name='splicingFAT_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/splicingFAT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfdt',
            name='ftth_splicing_fdt_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFDT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfdt',
            name='ftth_splicing_fdt_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFDT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfdt',
            name='ftth_splicing_fdt_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('FTTHProjects', 'images/ftth/InstallationTeam/splicingFDT/')),
        ),
        migrations.AlterField(
            model_name='ftthsplicingfdtimage',
            name='splicingFDT_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('FTTHProjects', 'images/ftth/InstallationTeam/splicingFDT/')),
        ),
    ]
