# Generated by Django 2.2.1 on 2019-08-16 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_core', '0001_initial'),
        ('erp_ftts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDuctInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('site_duct_installation_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/duct/%Y/%m/%d/')),
                ('site_duct_installation_image_2', models.ImageField(upload_to='images/ftts/CivilWorksTeam/duct/%Y/%m/%d/')),
                ('site_duct_installation_image_3', models.ImageField(upload_to='images/ftts/CivilWorksTeam/duct/%Y/%m/%d/')),
                ('site_duct_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.FTTSProject')),
                ('site_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_core.MainSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fttscivilteam',
            name='ftts_backfiling',
        ),
        migrations.RemoveField(
            model_name='fttscivilteam',
            name='ftts_pole_installation',
        ),
        migrations.DeleteModel(
            name='SiteBackfilling',
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='ftts_duct_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.SiteDuctInstallation'),
        ),
    ]
