# Generated by Django 2.2.1 on 2019-08-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fttssurvey',
            old_name='ftth_interception_point',
            new_name='ftts_interception_point',
        ),
    ]
