# Generated by Django 2.2.1 on 2019-08-22 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_ftts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FttsDailyTasksTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('task_date', models.DateTimeField(blank=True, null=True)),
                ('task_distance', models.FloatField(blank=True, null=True)),
                ('daily_task_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('ftts_cable_installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.SiteCableInstallation')),
                ('ftts_duct_installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.SiteDuctInstallation')),
                ('ftts_manhole_installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.ManHoleInstallation')),
                ('ftts_trenching', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.SiteTrenching')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.FttsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
