# Generated by Django 2.2.1 on 2019-09-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttsproject',
            name='description',
        ),
        migrations.AddField(
            model_name='fttssurveyphotos',
            name='work_day',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='fttssurvey',
            name='survey_photos',
            field=models.ManyToManyField(blank=True, null=True, to='erp_ftts.fttsSurveyPhotos'),
        ),
    ]
