# Generated by Django 2.2.1 on 2019-08-23 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_ftts', '0002_fttsdailytaskstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyManHoleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/manhole/%Y/%m/%d/')),
                ('manhole_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_manhole', models.FloatField(blank=True, null=True)),
                ('manhole_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySiteCableInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/cable/%Y/%m/%d/')),
                ('cable_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_cable', models.FloatField(blank=True, null=True)),
                ('cable_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySiteDuctInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/duct/%Y/%m/%d/')),
                ('duct_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_duct', models.FloatField(blank=True, null=True)),
                ('site_duct_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySiteInterception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/interception/%Y/%m/%d/')),
                ('interception_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_interception', models.FloatField(blank=True, null=True)),
                ('interception_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySiteTerminalInHse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/terminalinhse/%Y/%m/%d/')),
                ('terminal_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_terminal', models.FloatField(blank=True, null=True)),
                ('terminal_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DailySiteTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/trenching/%Y/%m/%d/')),
                ('trenching_date', models.DateField(blank=True, null=True, unique=True)),
                ('distance_trenched', models.FloatField(blank=True, null=True)),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, null=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManHoleInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manhole_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/manhole/%Y/%m/%d/')),
                ('manhole_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manholeimage', to='erp_ftts.DailyManHoleInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteCableInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cable_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/cable/%Y/%m/%d/')),
                ('cable_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cableimage', to='erp_ftts.DailySiteCableInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteDuctInstallationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_duct_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/duct/%Y/%m/%d/')),
                ('site_duct_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ductimage', to='erp_ftts.DailySiteDuctInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteInterceptionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('interception_image_1', models.ImageField(upload_to='images/ftts/InstallationTeam/interception/%Y/%m/%d/')),
                ('interception_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interceptionimage', to='erp_ftts.DailySiteInterception')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteTerminalInHseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('terminal_image_1', models.ImageField(upload_to='images/ftts/InstallationTeam/terminalinhse/%Y/%m/%d/')),
                ('terminal_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='terminalinhseimage', to='erp_ftts.DailySiteTerminalInHse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_trenching_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trenchingimage', to='erp_ftts.DailySiteTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='ftts_cable_installation',
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='ftts_duct_installation',
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='ftts_manhole_installation',
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='ftts_trenching',
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='fttsdailytaskstest',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='fttsinstallationteam',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='manholeinstallation',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='manholeinstallation',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='manholeinstallation',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='sitecableinstallation',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='sitecableinstallation',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='sitecableinstallation',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='siteductinstallation',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='siteductinstallation',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='siteductinstallation',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='siteinterception',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='siteinterception',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='siteinterception',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='siteterminalinhse',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='siteterminalinhse',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='siteterminalinhse',
            name='task_days',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='task_days',
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='ftts_activation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='ftts_activation_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manholeinstallation',
            name='site_manhole_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sitecableinstallation',
            name='site_cable_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteductinstallation',
            name='site_duct_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteinterception',
            name='site_interception_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='siteterminalinhse',
            name='site_terminal_in_hse_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenched_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_interception_image_1',
            field=models.ImageField(upload_to='images/ftts/InstallationTeam/interception/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_interception_image_2',
            field=models.ImageField(upload_to='images/ftts/InstallationTeam/interception/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_interception_image_3',
            field=models.ImageField(upload_to='images/ftts/InstallationTeam/interception/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='FttsDailyTasks',
        ),
        migrations.DeleteModel(
            name='FttsDailyTasksTest',
        ),
        migrations.AddField(
            model_name='dailysitetrenching',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dailytrenchings', to='erp_ftts.SiteTrenching'),
        ),
        migrations.AddField(
            model_name='dailysiteterminalinhse',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='terminalinhse', to='erp_ftts.SiteTerminalInHse'),
        ),
        migrations.AddField(
            model_name='dailysiteinterception',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='interception', to='erp_ftts.SiteInterception'),
        ),
        migrations.AddField(
            model_name='dailysiteductinstallation',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dailyduct', to='erp_ftts.SiteDuctInstallation'),
        ),
        migrations.AddField(
            model_name='dailysitecableinstallation',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cable', to='erp_ftts.SiteCableInstallation'),
        ),
        migrations.AddField(
            model_name='dailymanholeinstallation',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manhole', to='erp_ftts.ManHoleInstallation'),
        ),
    ]
