# Generated by Django 2.2.1 on 2019-08-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftts', '0003_auto_20190822_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyimage',
            old_name='site_trenching_comment',
            new_name='site_image_comment',
        ),
    ]
