# Generated by Django 2.2.1 on 2019-08-25 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_ftts', '0003_auto_20190823_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='FttsAccessApprovalCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_approval', models.FileField(upload_to='files/ftts/CivilWorksTeam/accessapproval/%Y/%m/%d/')),
                ('access_approval_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='civilaccessapproval', to='erp_ftts.FttsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='fttsinstallationteam',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/installationteam/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='FttsHealthDocumentsCivilTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_documents_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_picture', models.ImageField(blank=True, null=True, upload_to='images/ftts/HealthDocumentsCivilTeam/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('access_approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FttsAccessApprovalCivil')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='civilhealthdocuments', to='erp_ftts.FttsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FttsHealthDocsInstallationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('health_documents_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('safety_picture', models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeamFtts/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('access_approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_ftts.FttsAccessApprovalCivil')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthdocumentscivilteam', to='erp_ftts.FttsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FttsAccessApprovalInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_approval', models.FileField(upload_to='files/ftts/InstallationTeamFtts/accessapproval/%Y/%m/%d/')),
                ('access_approval_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accessapprovalcivil', to='erp_ftts.FttsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_ftts.FttsHealthDocumentsCivilTeam'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_ftts.FttsHealthDocsInstallationTeam'),
        ),
    ]
