# Generated by Django 2.2.1 on 2019-08-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_ftts', '0004_auto_20190822_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(unique=True)),
                ('distance_trenched', models.FloatField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/ftts/Casuals/trenching/%Y/%m/%d/')),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('site_trenching_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trenchingimage', to='erp_ftts.DailyTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='fttsdailycivilwork',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='fttsdailycivilwork',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='casuals_list',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='no_of_casuals_atsite',
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenched_distance',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='DailyImage',
        ),
        migrations.DeleteModel(
            name='FTtsDailyCivilWork',
        ),
        migrations.AddField(
            model_name='dailytrenching',
            name='site_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dailytrenchings', to='erp_ftts.SiteTrenching'),
        ),
    ]
