# Generated by Django 2.2.1 on 2019-08-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftthproject',
            name='project_type',
        ),
    ]
