# Generated by Django 2.2.1 on 2019-08-01 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_fiber_ftth', '0001_initial'),
        ('erp_construction', '0002_auto_20190801_1935'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interceptionpoint',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='ftthtrenching',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthtrenching',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthtrenching',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsurveyphotos',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsurveyphotos',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='ftth_interception_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.InterceptionPoint'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsurvey',
            name='survey_photos',
            field=models.ManyToManyField(to='erp_fiber_ftth.ftthSurveyPhotos'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfdt',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfdt',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfdt',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfat',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfat',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicingfat',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsplicingenclosure',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicingenclosure',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicingenclosure',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_encore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthSplicingEnclosure'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_fat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthSplicingFAT'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='ftth_splicing_fdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthSplicingFDT'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsplicing',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_splicing_encore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthCoreProvision'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_splicing_fat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthPowerLevels'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='ftth_splicing_fdt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthOTDRTraces'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthsignaltesting',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthprocurementteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthpowerlevels',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthpowerlevels',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthpowerlevels',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthpoleinstallation',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthotdrtraces',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthotdrtraces',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthotdrtraces',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_signal_testing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthSignalTesting'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='ftth_splicing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthSplicing'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthinstallationteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthcoreprovision',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcoreprovision',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcoreprovision',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthcommercialteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcommercialteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcommercialteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_backfiling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthBackfilling'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_cable_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthCableInstallation'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_pole_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthPoleInstallation'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='ftth_trenching',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FtthTrenching'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcivilteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthcableinstallation',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthbackfilling',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='ftthasbuilt',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ftthasbuilt',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftth.FTTHProject'),
        ),
        migrations.AddField(
            model_name='ftthasbuilt',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
