# Generated by Django 2.2.1 on 2019-08-02 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_project'),
        ('erp_fiber_ftth', '0002_remove_ftthproject_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ftthproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='ftthproject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='ftthproject',
            name='project_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_core.Project'),
            preserve_default=False,
        ),
    ]
