# Generated by Django 2.2.1 on 2019-07-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftth', '0002_ftthproject_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FTTHProject',
        ),
    ]
