# Generated by Django 2.2.1 on 2019-08-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftth', '0002_auto_20190801_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftthproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='ftthproject',
            name='initial_kmz',
            field=models.FileField(blank=True, null=True, upload_to='project/ftth/initialkmz/kmz/%Y/%m/%d/'),
        ),
    ]
