# Generated by Django 2.2.1 on 2019-08-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftth', '0003_auto_20190802_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftthsurvey',
            name='ftth_interception_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_fiber_ftth.InterceptionPoint'),
        ),
    ]
