# Generated by Django 2.2.1 on 2019-07-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftth', '0004_auto_20190726_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ftthproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Ftts', 'FTTS'), ('Ftth', 'FTTH'), ('Bts-Con', 'BTS Construction')], max_length=225, null=True),
        ),
    ]
