# Generated by Django 2.2.1 on 2019-09-17 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('fixed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='ceragontestcriteria',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragonriterias', to='fixed_data.Link'),
        ),
        migrations.AddField(
            model_name='ceragonpmaintenance',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragonmaintenamce', to='fixed_data.Consumable'),
        ),
        migrations.AddField(
            model_name='ceragonpmaintenance',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragonmaintenances', to='fixed_data.CeragonInstallation'),
        ),
        migrations.AddField(
            model_name='ceragonpmaintenance',
            name='test_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragonmaintenances', to='fixed_data.CeragontestCriteria'),
        ),
        migrations.AddField(
            model_name='ceragoninstallation',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragoninstallations', to='fixed_data.Consumable'),
        ),
        migrations.AddField(
            model_name='ceragoninstallation',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ceragoninstallations', to='fixed_data.Link'),
        ),
        migrations.AddField(
            model_name='ceragoninstallation',
            name='test_criteria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ceragoninstallations', to='fixed_data.CeragontestCriteria'),
        ),
        migrations.AlterUniqueTogether(
            name='wimaxpmaintenance',
            unique_together={('link', 'test_criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='ltepmaintenance',
            unique_together={('link', 'test_criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='fiberpmaintenance',
            unique_together={('link', 'test_criteria')},
        ),
        migrations.AlterUniqueTogether(
            name='ceragonpmaintenance',
            unique_together={('link', 'test_criteria')},
        ),
    ]
