# Generated by Django 2.2.1 on 2019-09-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_data', '0002_client_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='wimaxtestcriteria',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mimaxctriteria', to='fixed_data.Link'),
        ),
    ]
