# Generated by Django 2.2.1 on 2019-09-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_data', '0002_auto_20190918_1333'),
        ('fixed_data', '0003_auto_20190918_0009'),
    ]

    operations = [
    ]
