# Generated by Django 2.2.1 on 2019-09-17 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_data', '0003_wimaxtestcriteria_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('item', models.CharField(blank=True, max_length=250, null=True)),
                ('quantity', models.FloatField(default=0)),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='wimaxpmaintenance',
            unique_together={('link', 'test_criteria')},
        ),
        migrations.AddField(
            model_name='wimaxinstallation',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwinstallation', to='fixed_data.Consumable'),
        ),
    ]
