# Generated by Django 2.2.1 on 2019-09-17 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_data', '0004_auto_20190917_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumable',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='fixed_data.Link'),
        ),
        migrations.AlterField(
            model_name='wimaxinstallation',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwinstallation', to='fixed_data.Link'),
        ),
        migrations.AlterField(
            model_name='wimaxpmaintenance',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwpmaintenance', to='fixed_data.WiMaxInstallation'),
        ),
        migrations.AlterField(
            model_name='wimaxpmaintenance',
            name='test_criteria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwpmaintenances', to='fixed_data.WiMaxtestCriteria'),
        ),
    ]
