# Generated by Django 2.2.1 on 2019-09-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_data', '0005_auto_20190917_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='fiber_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='link',
            name='decomisioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wimaxpmaintenance',
            name='consumable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwpmaintenamce', to='fixed_data.Consumable'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issue', models.CharField(blank=True, max_length=250, null=True)),
                ('resolution', models.CharField(blank=True, max_length=250, null=True)),
                ('fiber_ready', models.BooleanField(default=False)),
                ('remacks', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='fixed_data.WiMaxInstallation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
