# Generated by Django 2.2.1 on 2019-07-22 15:17

from django.db import migrations, models
# Generated by Django 2.2.1 on 2019-07-22 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTTSProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_name', models.ManyToManyField(blank=True, to='erp_construction.Project')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            name='FttsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='FttsCommercialTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftts_quote', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/quote/%Y/%m/%d/')),
                ('ftts_po_requisition', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/requisition/%Y/%m/%d/')),
                ('ftts_wayleave_application', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/wayleaveapplication/%Y/%m/%d/')),
                ('ftts_project_plan', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/projectplan/%Y/%m/%d/')),
                ('ftts_initial_invoice', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/initialinvoice/%Y/%m/%d/')),
                ('ftts_po_client', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/poclient/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FttsSite')),
            ],
        ),
    ]
