# Generated by Django 2.2.1 on 2019-08-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_project'),
        ('erp_fiber_ftts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttsproject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='project_type',
        ),
        migrations.RemoveField(
            model_name='fttsproject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='project_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='erp_core.Project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='site_name',
            field=models.ManyToManyField(blank=True, related_name='fttsprojects', to='erp_construction.Site'),
        ),
    ]
