# Generated by Django 2.2.1 on 2019-07-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FttsProcurementTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftts_material_requisition', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/materialrequisition/%Y/%m/%d/')),
                ('ftts_material_receipt_order', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/receiptorder/%Y/%m/%d/')),
                ('ftts_pr', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/pr/%Y/%m/%d/')),
                ('ftts_po_quote_service', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/quoteservice/%Y/%m/%d/')),
                ('ftts_po_subcontractors', models.FileField(blank=True, null=True, upload_to='files/ftts/CommercialTeam/posubcontractors/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FttsSite')),
            ],
        ),
    ]
