# Generated by Django 2.2.1 on 2019-07-23 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0001_initial'),
        ('erp_construction', '0002_auto_20190723_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetrenching',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='siteterminalinhse',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='siteterminalinhse',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallation',
            name='daily_pole_installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SitePoleInstallationImage'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallation',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='siteinterception',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='siteinterception',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='siteintegration',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='siteintegration',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='sitecableinstallation',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='sitecableinstallation',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='sitebackfilling',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='sitebackfilling',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='siteasbuilt',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='siteasbuilt',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='site_name',
            field=models.ManyToManyField(blank=True, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='fttsprocurementteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='fttsprocurementteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='ftts_as_built',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteAsBuilt'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='ftts_inception',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteInterception'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='ftts_integration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteIntegration'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='ftts_terminal_in_hse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTerminalInHse'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='fttsinstallationteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='fttscommercialteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='fttscommercialteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='ftts_backfiling',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteBackfilling'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='ftts_cable_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteCableInstallation'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='ftts_pole_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SitePoleInstallation'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='ftts_trenching',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='fttscivilteam',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
