# Generated by Django 2.2.1 on 2019-07-23 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0002_auto_20190723_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
    ]
