# Generated by Django 2.2.1 on 2019-07-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0002_auto_20190726_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttsproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('FS', 'FTTS'), ('FH', 'FTTH'), ('BTS-CON', 'BTS Construction')], default='FTTS', max_length=2, null=True),
        ),
    ]
