# Generated by Django 2.2.1 on 2019-08-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0002_auto_20190802_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManHole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('manhole_No', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ManHoleInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('manhole_image_1', models.ImageField(upload_to='images/ftts/InstallationTeam/manhole/%Y/%m/%d/')),
                ('manhole_image_2', models.ImageField(upload_to='images/ftts/InstallationTeam/manhole/%Y/%m/%d/')),
                ('manhole_image_3', models.ImageField(upload_to='images/ftts/InstallationTeam/manhole/%Y/%m/%d/')),
                ('manhole_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('manhole', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.ManHole')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
                ('site_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='siteinterception',
            name='manhole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.ManHole'),
            preserve_default=False,
        ),
    ]
