# Generated by Django 2.2.1 on 2019-07-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0002_auto_20190730_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='site_trenching',
        ),
        migrations.RemoveField(
            model_name='projecttrenching',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projecttrenching',
            name='project_name',
        ),
        migrations.RenameField(
            model_name='sitetrenching',
            old_name='created_by',
            new_name='posted_by',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='backfilled_distance',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='project_trenching',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='trenched_distance',
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='site_backfilling_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/backfilling/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='site_backfilling_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/backfilling/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='site_backfilling_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/backfilling/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='site_cable_installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/cableinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='site_cable_installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/cableinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='site_cable_installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/cableinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='site_integration_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/integration/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='site_integration_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/integration/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='site_integration_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/integration/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_inception_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/inception/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_inception_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/inception/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_inception_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/inception/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='site_pole_installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='site_pole_installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='site_pole_installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='site_terminal_in_hse_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/terminalinhse/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='site_terminal_in_hse_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/terminalinhse/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='site_terminal_in_hse_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/InstallationTeam/terminalinhse/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.DeleteModel(
            name='FTTSCasualDailyRegister',
        ),
        migrations.DeleteModel(
            name='FTTSTrenchingImage',
        ),
        migrations.DeleteModel(
            name='ProjectTrenching',
        ),
    ]
