# Generated by Django 2.2.1 on 2019-07-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190723_1757'),
        ('erp_fiber_ftts', '0002_auto_20190723_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='fttsproject',
            name='site_name',
            field=models.ManyToManyField(blank=True, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
