# Generated by Django 2.2.1 on 2019-07-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0002_fttsprocurementteam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttsprocurementteam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fttsprocurementteam',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='fttssite',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='FttsCommercialTeam',
        ),
        migrations.DeleteModel(
            name='FttsProcurementTeam',
        ),
        migrations.DeleteModel(
            name='FttsSite',
        ),
    ]
