# Generated by Django 2.2.1 on 2019-07-23 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0003_sitepoleinstallationimage_posted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepoleinstallation',
            name='daily_pole_installation',
        ),
        migrations.AddField(
            model_name='sitepoleinstallation',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='daily_pole_installation_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SitePoleInstallation'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
