# Generated by Django 2.2.1 on 2019-07-30 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0003_auto_20190730_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttscivilteam',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='fttscivilteam',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttscivilteam',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='fttscommercialteam',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='fttscommercialteam',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttscommercialteam',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='fttsinstallationteam',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='fttsinstallationteam',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttsinstallationteam',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='fttsprocurementteam',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='fttsprocurementteam',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttsprocurementteam',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='site_name',
            field=models.ManyToManyField(blank=True, null=True, related_name='fttsprojects', to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='siteasbuilt',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='siteasbuilt',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='siteasbuilt',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
