# Generated by Django 2.2.1 on 2019-08-02 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0001_initial'),
        ('erp_fiber_ftts', '0004_auto_20190802_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhole',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.CreateModel(
            name='InterceptionPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interception_point_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='interceptionpointftts', to='users.Location')),
            ],
        ),
        migrations.CreateModel(
            name='fttsSurveyPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_image_1', models.ImageField(upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_image_2', models.ImageField(blank=True, null=True, upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_image_3', models.ImageField(blank=True, null=True, upload_to='images/ftth/survey/%Y/%m/%d/')),
                ('survey_images_comment', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
        ),
        migrations.CreateModel(
            name='fttsSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('site_latitude', models.FloatField()),
                ('site_longitude', models.FloatField()),
                ('distance_from_ip', models.FloatField(blank=True, null=True)),
                ('high_level_design', models.FileField(blank=True, null=True, upload_to='files/ftth/survey/highleveldesigns/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location')),
                ('ftth_interception_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.InterceptionPoint')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('site_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
                ('survey_photos', models.ManyToManyField(to='erp_fiber_ftts.fttsSurveyPhotos')),
            ],
        ),
    ]
