# Generated by Django 2.2.1 on 2019-07-23 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0004_auto_20190723_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image',
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image1',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/poleinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='site_trenching_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/'),
        ),
    ]
