# Generated by Django 2.2.1 on 2019-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0004_auto_20190730_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttsproject',
            name='site_name',
            field=models.ManyToManyField(blank=True, related_name='fttsprojects', to='erp_construction.Site'),
        ),
    ]
