# Generated by Django 2.2.1 on 2019-07-31 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0003_auto_20190730_1936'),
        ('erp_fiber_ftts', '0005_auto_20190730_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTTSCasualDailyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('ftts_casual', models.ManyToManyField(related_name='fttscasualregister', to='users.Casual')),
                ('project_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
            options={
                'unique_together': {('site_name', 'work_day')},
            },
        ),
        migrations.CreateModel(
            name='DailyCivilWorkProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('trenched_distance', models.FloatField(blank=True, null=True)),
                ('backfilled_distance', models.FloatField(blank=True, null=True)),
                ('duct_installed_length', models.FloatField(blank=True, null=True)),
                ('cable_installed_length', models.FloatField(blank=True, null=True)),
                ('pole_installed', models.IntegerField(blank=True, null=True)),
                ('manhole_installed', models.IntegerField(blank=True, null=True)),
                ('site_dailyproduction_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
                ('site_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
            options={
                'unique_together': {('site_name', 'work_day')},
            },
        ),
    ]
