# Generated by Django 2.2.1 on 2019-07-23 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0005_auto_20190723_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitepoleinstallationimage',
            old_name='daily_pole_installation_image',
            new_name='pole_installation_task',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_comment',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_1',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_2',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_3',
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.CreateModel(
            name='TrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('site_trenching_image_1', models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_image_2', models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_image_3', models.ImageField(blank=True, null=True, upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('trenching_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
