# Generated by Django 2.2.1 on 2019-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0005_auto_20190726_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttsproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('FTTS', 'FTTS'), ('FTTH', 'FTTH'), ('BTS-CON', 'BTS Construction')], default='FS', max_length=200, null=True),
        ),
    ]
