# Generated by Django 2.2.1 on 2019-07-31 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0006_dailycivilworkproduction_fttscasualdailyregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttscasualdailyregister',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttscasualdailyregister',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
