# Generated by Django 2.2.1 on 2019-07-23 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190723_2148'),
        ('erp_fiber_ftts', '0007_fttsproject_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='trenchingimage',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
