# Generated by Django 2.2.1 on 2019-07-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0007_auto_20190726_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttsproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Ftts', 'FTTS'), ('Ftts', 'FTTH'), ('Bts-Con', 'BTS Construction')], max_length=225, null=True),
        ),
    ]
