# Generated by Django 2.2.1 on 2019-07-26 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190726_1123'),
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0008_auto_20190726_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trenching_day', models.IntegerField()),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_comment',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_1',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_2',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_image_3',
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AlterField(
            model_name='fttsproject',
            name='project_type',
            field=models.CharField(blank=True, choices=[('Ftts', 'FTTS'), ('Ftth', 'FTTH'), ('Bts-Con', 'BTS Construction')], max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.CreateModel(
            name='FTTSTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('site_trenching_image_1', models.ImageField(upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_image_2', models.ImageField(upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_image_3', models.ImageField(upload_to='images/ftts/CivilWorksTeam/trenching/%Y/%m/%d/')),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('daily_image', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.DailyTrenchingImage')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
                ('site_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailytrenchingimage',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AddField(
            model_name='dailytrenchingimage',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='dailytrenchingimage',
            name='site_trenching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching'),
        ),
    ]
