# Generated by Django 2.2.1 on 2019-07-23 21:24

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0008_auto_20190723_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTS/images/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTS/images/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallationimage',
            name='site_pole_installation_image3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('FTTS/images/CivilWorksTeam/poleinstallation/%Y/%m/%d/')),
        ),
        migrations.AlterField(
            model_name='trenchingimage',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
