# Generated by Django 2.2.1 on 2019-07-26 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0009_auto_20190726_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='daily_image',
        ),
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='trenching_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fttstrenchingimage',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.AlterField(
            model_name='fttstrenchingimage',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.DeleteModel(
            name='DailyTrenchingImage',
        ),
    ]
