# Generated by Django 2.2.1 on 2019-07-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190723_2148'),
        ('erp_fiber_ftts', '0009_auto_20190724_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepoleinstallation',
            name='site_name',
        ),
        migrations.AddField(
            model_name='sitepoleinstallationimage',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
