# Generated by Django 2.2.1 on 2019-07-26 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190726_1123'),
        ('erp_fiber_ftts', '0011_auto_20190726_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='trench_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='trenching_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fttstrenchingimage',
            name='daily_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching'),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='project_name',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.DeleteModel(
            name='DailyTrenchingImage',
        ),
    ]
