# Generated by Django 2.2.1 on 2019-07-26 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190726_1123'),
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0012_auto_20190726_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='daily_image',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_name',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='site_trenching_comment',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='trench_distance',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='trenching_day',
        ),
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='trenching_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='project_name',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject'),
        ),
        migrations.CreateModel(
            name='DailyTrenchingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trenching_day', models.DateField(blank=True, null=True)),
                ('site_trenching_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
                ('site_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
                ('site_trenching', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
