# Generated by Django 2.2.1 on 2019-07-26 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0013_auto_20190726_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='trenching_day',
        ),
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='daily_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.DailyTrenchingImage'),
        ),
    ]
