# Generated by Django 2.2.1 on 2019-07-26 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190726_1123'),
        ('erp_fiber_ftts', '0014_auto_20190726_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='daily_image',
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fttsproject',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='site_trenching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.SiteTrenching'),
        ),
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='trenching_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
        migrations.AlterField(
            model_name='siteasbuilt',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitebackfilling',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitecableinstallation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteintegration',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinterception',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitepoleinstallation',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteterminalinhse',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sitetrenching',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DailyTrenchingImage',
        ),
    ]
