# Generated by Django 2.2.1 on 2019-07-26 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0015_auto_20190726_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetrenching',
            old_name='posted_by',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='sitetrenching',
            name='project_name',
        ),
        migrations.CreateModel(
            name='ProjectTrenching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.FTTSProject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='site_trenching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_fiber_ftts.ProjectTrenching'),
        ),
    ]
