# Generated by Django 2.2.1 on 2019-07-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0016_auto_20190726_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='site_name',
        ),
    ]
