# Generated by Django 2.2.1 on 2019-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0017_remove_fttstrenchingimage_site_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttstrenchingimage',
            name='project_name',
        ),
    ]
