# Generated by Django 2.2.1 on 2019-07-26 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0018_remove_fttstrenchingimage_project_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitetrenching',
            old_name='site_trenching',
            new_name='project_trenching',
        ),
    ]
