# Generated by Django 2.2.1 on 2019-07-27 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0019_auto_20190726_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitetrenching',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site'),
        ),
    ]
