# Generated by Django 2.2.1 on 2019-07-27 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0021_auto_20190727_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fttstrenchingimage',
            name='site_trenching',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fttstrenchingimages', to='erp_fiber_ftts.SiteTrenching'),
        ),
    ]
