# Generated by Django 2.2.1 on 2019-07-27 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190726_1123'),
        ('users', '0001_initial'),
        ('erp_fiber_ftts', '0022_auto_20190727_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='fttstrenchingimage',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='backfilled_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitetrenching',
            name='trenched_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FTTSCasualDailyRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trenching_day', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('ftts_casual', models.ManyToManyField(related_name='fttscasualregister', to='users.Casual')),
                ('project_trenching', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fttscasualregisterproject', to='erp_fiber_ftts.ProjectTrenching')),
                ('site_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
