# Generated by Django 2.2.1 on 2019-07-27 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_fiber_ftts', '0023_auto_20190727_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fttscasualdailyregister',
            name='project_trenching',
        ),
        migrations.AddField(
            model_name='fttscasualdailyregister',
            name='site_trenching',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fttscasualregisterprojectsite', to='erp_fiber_ftts.SiteTrenching'),
        ),
    ]
