<<<<<<< HEAD:erp_core/migrations/0001_initial.py
# Generated by Django 2.2.1 on 2019-09-19 13:46
=======
# Generated by Django 2.2.1 on 2019-09-10 07:21
>>>>>>> d0eeb2c7a0ce3a1e18dcb86288d03e4b1deb869e:inventory/migrations/0001_initial.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD:erp_core/migrations/0001_initial.py
=======
        ('users', '0002_projectteamftth_projectteamftts_teammembertype'),
>>>>>>> d0eeb2c7a0ce3a1e18dcb86288d03e4b1deb869e:inventory/migrations/0001_initial.py
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
