# Generated by Django 2.2.1 on 2019-08-27 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_ftts', '0001_initial'),
        ('erp_ftth', '0001_initial'),
        ('erp_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiberBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('project_name', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject')),
                ('site_name', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.FttsSite')),
            ],
        ),
    ]
