# Generated by Django 2.2.1 on 2019-08-27 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0002_fiberbudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberbudget',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftth.FTTHProject'),
        ),
        migrations.AlterField(
            model_name='fiberbudget',
            name='site_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_ftts.FttsSite'),
        ),
    ]
