# Generated by Django 2.2.1 on 2019-08-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0004_auto_20190827_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberbudget',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
