# Generated by Django 2.2.1 on 2019-08-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_core', '0005_auto_20190827_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiberbudget',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fiberbudget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
