<<<<<<< HEAD
# Generated by Django 2.2.1 on 2019-09-19 13:46

from django.conf import settings
=======
# Generated by Django 2.2.1 on 2019-09-10 07:21

>>>>>>> d0eeb2c7a0ce3a1e18dcb86288d03e4b1deb869e
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.FCM_DEVICE_MODEL),
=======
        ('users', '0002_projectteamftth_projectteamftts_teammembertype'),
>>>>>>> d0eeb2c7a0ce3a1e18dcb86288d03e4b1deb869e
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
<<<<<<< HEAD
                ('receiver', models.ManyToManyField(blank=True, null=True, to=settings.FCM_DEVICE_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.FCM_DEVICE_MODEL)),
=======
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcmreceiver', to='users.CustomUser')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcmsender', to='users.CustomUser')),
>>>>>>> d0eeb2c7a0ce3a1e18dcb86288d03e4b1deb869e
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
