# Generated by Django 2.2.1 on 2019-09-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcm_messaging', '0002_auto_20190918_1333'),
        ('fcm_messaging', '0002_auto_20190917_2340'),
    ]

    operations = [
    ]
