# Generated by Django 2.2.1 on 2019-05-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btsinstallationtask',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='electricalearthing',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='generatorinstallation',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='kplcsolarimage',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='mwinstallationtask',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='reticulationapsinstallation',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
        migrations.RenameField(
            model_name='undergroundtasks',
            old_name='casuals_atsite',
            new_name='no_of_casuals_atsite',
        ),
    ]
