# Generated by Django 2.2.1 on 2019-06-24 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilworksteam',
            name='access_approvals_field',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='access_approvals_field',
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='safety_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/HealthDocumentsCivilTeam/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='safety_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/HealthDocumentsInstallationTeam/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='WarrantyCertificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilworks_installation_certificate', models.FileField(blank=True, null=True, upload_to='files/WarrantyCertificates/civilworks/%Y/%m/%d/')),
                ('connectors_torque_certificate', models.FileField(blank=True, null=True, upload_to='files/WarrantyCertificates/connectorsTorque/%Y/%m/%d/')),
                ('safe_to_climb_certificate', models.FileField(blank=True, null=True, upload_to='files/WarrantyCertificates/SafeToClimb/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='TestCetificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cube_test_7days', models.FileField(blank=True, null=True, upload_to='files/TestCertificates/cubetest7/%Y/%m/%d/')),
                ('cube_test_28days', models.FileField(blank=True, null=True, upload_to='files/TestCertificates/cubetest28/%Y/%m/%d/')),
                ('earth_test', models.FileField(blank=True, null=True, upload_to='files/TestCertificates/earthtest/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
    ]
