# Generated by Django 2.2.1 on 2019-05-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='employee_no',
            new_name='employee_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employee_no',
            new_name='employee_id',
        ),
    ]
