# Generated by Django 2.2.1 on 2019-05-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationteam',
            name='conditional_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/conditionalcert/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='final_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/finalcert/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='rf_document',
            field=models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/rf/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='snag_document',
            field=models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/snag/%Y/%m/%d/'),
        ),
    ]
