# Generated by Django 2.2.1 on 2019-08-26 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('erp_construction', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycertificate',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='warrantycertificate',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='undergroundtasks',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='undergroundtasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerpaintimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerpaintimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towererectionimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towererectionimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerbasesubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerbasesubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerbaseimage',
            name='day_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='towerbaseimages', to='erp_construction.TowerBaseDate'),
        ),
        migrations.AddField(
            model_name='towerbasedate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbasedates', to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='antenna_coax_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.AntennaCoaxInstallImage'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='cable_ways',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.CableWaysImage'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='tower_erection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerErectionImage'),
        ),
        migrations.AddField(
            model_name='towerantennacoaximage',
            name='tower_painting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerPaintImage'),
        ),
        migrations.AddField(
            model_name='testcetificate',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='testcetificate',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='telecomtasks',
            name='Installation_of_BTS',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BTSinstallationTask'),
        ),
        migrations.AddField(
            model_name='telecomtasks',
            name='Installation_of_MW_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.MWInstallationTask'),
        ),
        migrations.AddField(
            model_name='telecomtasks',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='telecomtasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='steelfixformworkimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steelfixformworkimages', to='erp_construction.SteelFixFormworkDate'),
        ),
        migrations.AddField(
            model_name='steelfixformworkdate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='steelfixformworkdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steelfixformworkdates', to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AddField(
            model_name='siteclearingsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='siteclearingimage',
            name='day_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SiteClearingDate'),
        ),
        migrations.AddField(
            model_name='siteclearingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteclearingdates', to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='razorelectricfenceimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='razorelectricfenceimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='projectpurchaseorders',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='projectcosting',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='procurementteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='procurementteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='mwinstallationtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='mwinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='kplcsolarimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='kplcsolarimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='issues',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='issues',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuess', to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='electrical_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ElectricalTasks'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_construction.HealthDocumentsInstallationTeam'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='issues',
            field=models.ManyToManyField(blank=True, to='erp_construction.Issues'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='telecom_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TelecomTasks'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='access_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.AccessApprovalInstallation'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='access_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.AccessApprovalCivil'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthdocumentscivilteam', to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='generatorinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='generatorinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='gateinstallationimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='gateinstallationimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='foundfootpoursubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='foundfootpoursubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='foundfootpourimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourDate'),
        ),
        migrations.AddField(
            model_name='foundfootpourdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='foundfootpourdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourSubTask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='blinding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlindingSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='concrete_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='concrete_pour_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='excavation_tower_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='setting_site_clearing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AddField(
            model_name='excavationsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='excavationsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='excavationimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationDate'),
        ),
        migrations.AddField(
            model_name='excavationdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='excavationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='Earthing_connections_and_testing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ElectricalEarthing'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='Electricalreticulation_APSInstallation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ReticulationAPSinstallation'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='Generator_and_Fuel_Tank_Installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.GeneratorInstallation'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='KPLC_solar_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.KPLCSolarImage'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='Underground_ducting_and_manholes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.UndergroundTasks'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='electricaltasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='electricalearthing',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='electricalearthing',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretepourimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretepourdates', to='erp_construction.ConcretePourDate'),
        ),
        migrations.AddField(
            model_name='concretepourdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretepourdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretepourdates', to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretecuringperiodimages', to='erp_construction.ConcreteCuringPeriodDate'),
        ),
        migrations.AddField(
            model_name='concretecuringperioddate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretecuringperioddate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretecuringperioddates', to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='po_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ProjectPurchaseOrders'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='project_costing_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ProjectCosting'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='bs241_and_generator_slabs_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241AndGeneratorSlabTask'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundationCreationTask'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_construction.HealthDocumentsCivilTeam'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BoundaryWallImage'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='tower_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerAntennaCoaxImage'),
        ),
        migrations.AddField(
            model_name='cablewaysimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='cablewaysimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BtsProject'),
        ),
        migrations.AddField(
            model_name='btsproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='btsproject',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ProjectIcon'),
        ),
        migrations.AddField(
            model_name='btsinstallationtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='btsinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodDate'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperioddate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='block_construction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstImage'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourImage'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='gate_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.GateInstallationImage'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='boundarywallimage',
            name='razor_electric_fence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.RazorElectricFenceImage'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='blindingsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blindingsubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='blindingimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingimages', to='erp_construction.BlindingDate'),
        ),
        migrations.AddField(
            model_name='blindingdate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blindingdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingdates', to='erp_construction.BlindingSubtask'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstallimage',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstallimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='accessapprovalinstallation',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='accessapprovalcivil',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accessapprovalcivil', to='erp_construction.BtsSite'),
        ),
    ]
