# Generated by Django 2.2.1 on 2019-06-13 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concretepourcuringperiodimage',
            old_name='concrete_pour_curing_comment',
            new_name='concrete_pour_curing_period_comment',
        ),
        migrations.RenameField(
            model_name='concretepourcuringperiodimage',
            old_name='concrete_pour_curing_image_1',
            new_name='concrete_pour_curing_period_image_1',
        ),
        migrations.RenameField(
            model_name='concretepourcuringperiodimage',
            old_name='concrete_pour_curing_image_2',
            new_name='concrete_pour_curing_period_image_2',
        ),
        migrations.RenameField(
            model_name='concretepourcuringperiodimage',
            old_name='concrete_pour_curing_image_3',
            new_name='concrete_pour_curing_period_image_3',
        ),
        migrations.RemoveField(
            model_name='btsandgeneatorslabsimage',
            name='concrete_pour_period',
        ),
        migrations.AddField(
            model_name='foundationimage',
            name='concrete_pour_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourCuringPeriodImage'),
        ),
    ]
