# Generated by Django 2.2.1 on 2019-06-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundationimage',
            old_name='concrete_pour_period',
            new_name='concrete_curing_period',
        ),
        migrations.RenameField(
            model_name='foundationimage',
            old_name='concrete_pour_curing',
            new_name='concrete_pour_curing_period',
        ),
    ]
