# Generated by Django 2.2.1 on 2019-08-27 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrantycertificate',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='warrantycertificate',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='undergroundtaskimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='undergroundtaskimages', to='erp_construction.UndergroundTaskDate'),
        ),
        migrations.AddField(
            model_name='undergroundtaskdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='undergroundtaskdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='undergroundtaskdates', to='erp_construction.UndergroundTask'),
        ),
        migrations.AddField(
            model_name='undergroundtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='undergroundtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerpaintsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerpaintsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerpaintimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towerpaintimages', to='erp_construction.TowerPaintDate'),
        ),
        migrations.AddField(
            model_name='towerpaintdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerpaintdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerpaintdates', to='erp_construction.TowerPaintSubtask'),
        ),
        migrations.AddField(
            model_name='towererectionsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towererectionsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towererectionimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='towererectionimages', to='erp_construction.TowerErectionDate'),
        ),
        migrations.AddField(
            model_name='towererectiondate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towererectiondate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towererectiondates', to='erp_construction.TowerErectionSubtask'),
        ),
        migrations.AddField(
            model_name='towerbasesubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerbasesubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerbaseimage',
            name='day_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbaseimages', to='erp_construction.TowerBaseDate'),
        ),
        migrations.AddField(
            model_name='towerbasedate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbasedates', to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='antenna_coax_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.AntennaCoaxInstallSubtask'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='cable_ways',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.CableWaysSubtask'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='tower_erection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerErectionSubtask'),
        ),
        migrations.AddField(
            model_name='towerantennacoaxtask',
            name='tower_painting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerPaintSubtask'),
        ),
        migrations.AddField(
            model_name='testcetificate',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='testcetificate',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='telecomtask',
            name='Installation_of_BTS',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BTSinstallationTask'),
        ),
        migrations.AddField(
            model_name='telecomtask',
            name='Installation_of_MW_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.MWInstallationTask'),
        ),
        migrations.AddField(
            model_name='telecomtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='telecomtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='steelfixformworkimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steelfixformworkimages', to='erp_construction.SteelFixFormworkDate'),
        ),
        migrations.AddField(
            model_name='steelfixformworkdate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='steelfixformworkdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steelfixformworkdates', to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AddField(
            model_name='siteclearingsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='siteclearingsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='siteclearingimage',
            name='day_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SiteClearingDate'),
        ),
        migrations.AddField(
            model_name='siteclearingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteclearingdates', to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallationimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reticulationAPSinstallationimages', to='erp_construction.ReticulationAPSinstallationDate'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallationdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reticulationAPSinstallationdates', to='erp_construction.ReticulationAPSinstallation'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='reticulationapsinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='razorelectricfencesubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='razorelectricfencesubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='razorelectricfenceimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razorelectricfenceimages', to='erp_construction.RazorElectricFenceDate'),
        ),
        migrations.AddField(
            model_name='razorelectricfencedate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='razorelectricfencedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razorelectricfencedates', to='erp_construction.RazorElectricFenceSubtask'),
        ),
        migrations.AddField(
            model_name='projectpurchaseorder',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='projectcosting',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='procurementteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='procurementteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='mwinstallationtaskimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mwinstallationtaskimages', to='erp_construction.MWInstallationTaskDate'),
        ),
        migrations.AddField(
            model_name='mwinstallationtaskdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='mwinstallationtaskdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mwinstallationtaskdates', to='erp_construction.MWInstallationTask'),
        ),
        migrations.AddField(
            model_name='mwinstallationtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='mwinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='kplcsolarsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='kplcsolarsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='kplcsolarimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kplcsolarimages', to='erp_construction.KPLCSolarDate'),
        ),
        migrations.AddField(
            model_name='kplcsolardate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='kplcsolardate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kplcsolardates', to='erp_construction.KPLCSolarSubtask'),
        ),
        migrations.AddField(
            model_name='issue',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issues', to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='electrical_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ElectricalTask'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_construction.HealthDocumentsInstallationTeam'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='issue',
            field=models.ManyToManyField(blank=True, to='erp_construction.Issue'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='telecom_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TelecomTask'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='access_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.AccessApprovalInstallation'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='healthdocumentsinstallationteam',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='access_approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.AccessApprovalCivil'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='healthdocumentscivilteam',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='healthdocumentscivilteam', to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='generatorinstallationimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generatorinstallationimages', to='erp_construction.AntennaCoaxInstallDate'),
        ),
        migrations.AddField(
            model_name='generatorinstallationdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='generatorinstallationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generatorinstallationdates', to='erp_construction.AntennaCoaxInstallSubtask'),
        ),
        migrations.AddField(
            model_name='generatorinstallation',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='generatorinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='gateinstallationsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='gateinstallationsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='gateinstallationimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gateinstallationimages', to='erp_construction.GateInstallationDate'),
        ),
        migrations.AddField(
            model_name='gateinstallationdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='gateinstallationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateinstallationdates', to='erp_construction.GateInstallationSubtask'),
        ),
        migrations.AddField(
            model_name='foundfootpoursubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='foundfootpoursubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='foundfootpourimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foundfootpourimages', to='erp_construction.FoundFootPourDate'),
        ),
        migrations.AddField(
            model_name='foundfootpourdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='foundfootpourdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foundfootpourdates', to='erp_construction.FoundFootPourSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='blinding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlindingSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='concrete_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='concrete_pour_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='excavation_tower_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='setting_site_clearing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AddField(
            model_name='foundationcreationtask',
            name='steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AddField(
            model_name='excavationsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='excavationsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='excavationimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excavationimages', to='erp_construction.ExcavationDate'),
        ),
        migrations.AddField(
            model_name='excavationdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='excavationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excavationdates', to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='earthing_connections_and_testing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ElectricalEarthing'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='electricalreticulation_APSInstallation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ReticulationAPSinstallation'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='generator_and_Fuel_Tank_Installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.GeneratorInstallation'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='kPLC_solar_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.KPLCSolarImage'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='electricaltask',
            name='underground_ducting_and_manholes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.UndergroundTask'),
        ),
        migrations.AddField(
            model_name='electricalearthingimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricalearthingimages', to='erp_construction.ElectricalEarthingDate'),
        ),
        migrations.AddField(
            model_name='electricalearthingdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='electricalearthingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electricalearthingdates', to='erp_construction.ElectricalEarthing'),
        ),
        migrations.AddField(
            model_name='electricalearthing',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='electricalearthing',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretepourimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretepourdates', to='erp_construction.ConcretePourDate'),
        ),
        migrations.AddField(
            model_name='concretepourdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretepourdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretepourdates', to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretecuringperiodimages', to='erp_construction.ConcreteCuringPeriodDate'),
        ),
        migrations.AddField(
            model_name='concretecuringperioddate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='concretecuringperioddate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concretecuringperioddates', to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='po_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ProjectPurchaseOrder'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='project_costing_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ProjectCosting'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='bs241_and_generator_slabs_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241AndGeneratorSlabTask'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundationCreationTask'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='health_documents',
            field=models.ManyToManyField(blank=True, to='erp_construction.HealthDocumentsCivilTeam'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BoundaryWallTask'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='tower_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerAntennaCoaxTask'),
        ),
        migrations.AddField(
            model_name='cablewayssubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='cablewayssubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='cablewaysimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cablewaysimages', to='erp_construction.CableWaysDate'),
        ),
        migrations.AddField(
            model_name='cablewaysdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='cablewaysdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cablewaysdates', to='erp_construction.CableWaysSubtask'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BtsProject'),
        ),
        migrations.AddField(
            model_name='btsproject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
        ),
        migrations.AddField(
            model_name='btsproject',
            name='icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ProjectIcon'),
        ),
        migrations.AddField(
            model_name='btsinstallationtaskimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='btsinstallationtaskimages', to='erp_construction.BTSinstallationTaskDate'),
        ),
        migrations.AddField(
            model_name='btsinstallationtaskdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='btsinstallationtaskdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='btsinstallationtaskdates', to='erp_construction.BTSinstallationTask'),
        ),
        migrations.AddField(
            model_name='btsinstallationtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='btsinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bs241Concretepourcuringperiodimages', to='erp_construction.BS241ConcretePourCuringPeriodDate'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperioddate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bs241Concretepourcuringperioddates', to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AddField(
            model_name='bs241andgeneratorslabtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='block_construction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlockworkPanelConstSubtask'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='engineers_atsite',
            field=models.ManyToManyField(blank=True, to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundFootPourSubtask'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='gate_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.GateInstallationSubtask'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='razor_electric_fence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.RazorElectricFenceSubtask'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstDate'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstdate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blockworkpanelconstdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstSubtask'),
        ),
        migrations.AddField(
            model_name='blindingsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blindingsubtask',
            name='project_name',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='blindingimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingimages', to='erp_construction.BlindingDate'),
        ),
        migrations.AddField(
            model_name='blindingdate',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='blindingdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingdates', to='erp_construction.BlindingSubtask'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstallsubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstallsubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstallimage',
            name='day_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='antennacoaxinstallimages', to='erp_construction.AntennaCoaxInstallDate'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstalldate',
            name='casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
        migrations.AddField(
            model_name='antennacoaxinstalldate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antennacoaxinstalldates', to='erp_construction.AntennaCoaxInstallSubtask'),
        ),
        migrations.AddField(
            model_name='accessapprovalinstallation',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.AddField(
            model_name='accessapprovalcivil',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='accessapprovalcivil', to='erp_construction.BtsSite'),
        ),
    ]
