# Generated by Django 2.2.1 on 2019-05-30 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationteam',
            name='as_built',
            field=models.FileField(blank=True, null=True, upload_to='files/SafaricomTeam/as_built/%Y/%m/%d/'),
        ),
    ]
