# Generated by Django 2.2.1 on 2019-07-30 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kpi',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='subtask',
            name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='category_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='posted_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Kpi',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
