# Generated by Django 2.2.1 on 2019-05-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='employee_id',
        ),
    ]
