# Generated by Django 2.2.1 on 2019-06-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190613_1247'),
        ('erp_construction', '0002_auto_20190613_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='BS241AndGeneatorSlabsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bs241_and_generator_slabs_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BS241ConcretePourCuringPeriodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('bs241_concrete_pour_curing_period_image_1', models.ImageField(upload_to='images/CivilWorksTeam/BS241ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('bs241_concrete_pour_curing_period_image_2', models.ImageField(upload_to='images/CivilWorksTeam/BS241ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('bs241_concrete_pour_curing_period_image_3', models.ImageField(upload_to='images/CivilWorksTeam/BS241ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('bs241_concrete_pour_curing_period_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(to='users.Casual')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.RenameModel(
            old_name='ConcretePourCuringPeriodImage',
            new_name='ConcreteCuringPeriodImage',
        ),
        migrations.RenameModel(
            old_name='ConcretePourCuringImage',
            new_name='ConcretePourImage',
        ),
        migrations.RemoveField(
            model_name='civilworksteam',
            name='bts_and_generator_slabs_images',
        ),
        migrations.DeleteModel(
            name='BTSAndGeneatorSlabsImage',
        ),
        migrations.AddField(
            model_name='bs241andgeneatorslabsimage',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241ConcretePourCuringPeriodImage'),
        ),
        migrations.AddField(
            model_name='bs241andgeneatorslabsimage',
            name='engineers_atsite',
            field=models.ManyToManyField(to='users.Engineer'),
        ),
        migrations.AddField(
            model_name='bs241andgeneatorslabsimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ExcavationImage'),
        ),
        migrations.AddField(
            model_name='bs241andgeneatorslabsimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='bs241_and_generator_slabs_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241AndGeneatorSlabsImage'),
        ),
    ]
