# Generated by Django 2.2.1 on 2019-07-15 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190715_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementteam',
            name='po_electrical_materials_quantity',
        ),
        migrations.RemoveField(
            model_name='procurementteam',
            name='po_steel_quantity',
        ),
    ]
