# Generated by Django 2.2.1 on 2019-09-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190919_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialteam',
            name='customer_issued_quotation',
            field=models.FileField(blank=True, null=True, upload_to='files/CommercialTeam/customer_issued_quotation/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='drawings_revised_approved',
            field=models.FileField(blank=True, null=True, upload_to='files/CommercialTeam/drawings_revised_approved/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='commercialteam',
            name='tower_type_allocated',
            field=models.FileField(blank=True, null=True, upload_to='files/CommercialTeam/tower_type_allocated/%Y/%m/%d/'),
        ),
    ]
