# Generated by Django 2.2.1 on 2019-08-23 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190823_1439'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectIcons',
            new_name='ProjectIcon',
        ),
    ]
