# Generated by Django 2.2.1 on 2019-06-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190624_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='issue_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/issues/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='issues',
            name='issue_sorted_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/issues/%Y/%m/%d/'),
        ),
    ]
