# Generated by Django 2.2.1 on 2019-05-28 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_projecticons'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ProjectIcons'),
        ),
    ]
