# Generated by Django 2.2.1 on 2019-05-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_civilworksteam_healthdocumentscivilteam_procurementteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_id',
            field=models.CharField(max_length=20),
        ),
    ]
