# Generated by Django 2.2.1 on 2019-05-28 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190528_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricaltasks',
            name='Earthing_connections_and_testing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ElectricalEarthing'),
        ),
        migrations.AlterField(
            model_name='electricaltasks',
            name='Electricalreticulation_APSInstallation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ReticulationAPSinstallation'),
        ),
        migrations.AlterField(
            model_name='electricaltasks',
            name='Generator_and_Fuel_Tank_Installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.GeneratorInstallation'),
        ),
        migrations.AlterField(
            model_name='electricaltasks',
            name='KPLC_solar_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.KPLCSolarImage'),
        ),
        migrations.AlterField(
            model_name='electricaltasks',
            name='Underground_ducting_and_manholes',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.UndergroundTasks'),
        ),
        migrations.AlterField(
            model_name='telecomtasks',
            name='Installation_of_BTS',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BTSinstallationTask'),
        ),
        migrations.AlterField(
            model_name='telecomtasks',
            name='Installation_of_MW_links',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.MWInstallationTask'),
        ),
    ]
