# Generated by Django 2.2.1 on 2019-08-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0002_auto_20190822_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteclearing',
            name='no_of_casuals_atsite',
        ),
    ]
