# Generated by Django 2.2.1 on 2019-09-26 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_projectteamftth_projectteamftts_teammembertype'),
        ('erp_construction', '0002_auto_20190919_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='btssite',
            name='integration_parameter',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/integrationparameters/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='ip_plan',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/ipplans/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='rfi',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/rfis/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='rof_8',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/rof8s/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='sign_off',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/signoffs/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='IRROF7Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tower_complete', models.FileField(blank=True, null=True, upload_to='files/IRROF7Frees/towercomplete/%Y/%m/%d/')),
                ('free_issue_material', models.FileField(blank=True, null=True, upload_to='files/IRROF7Frees/freeissuematerials/%Y/%m/%d/')),
                ('link_material', models.FileField(blank=True, null=True, upload_to='files/IRROF7Frees/linkmaterials/%Y/%m/%d/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
        ),
    ]
