# Generated by Django 2.2.1 on 2019-07-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190624_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mwinstallationtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
