# Generated by Django 2.2.1 on 2019-05-06 09:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190506_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(upload_to='images/CivilWorksTeam/foundation/%Y/%m/%d/'), size=None),
        ),
    ]
