# Generated by Django 2.2.1 on 2019-05-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190521_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementteam',
            name='po_electrical_materials',
            field=models.FileField(blank=True, null=True, upload_to='files/ProcurementTeam/poelectrical/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='po_steel',
            field=models.FileField(blank=True, null=True, upload_to='files/ProcurementTeam/posteel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='po_subcontractors',
            field=models.FileField(blank=True, null=True, upload_to='files/ProcurementTeam/posubcontractor/%Y/%m/%d/'),
        ),
    ]
