# Generated by Django 2.2.1 on 2019-05-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190529_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installationteam',
            old_name='rf_document',
            new_name='rfi_document',
        ),
        migrations.RenameField(
            model_name='installationteam',
            old_name='rf_document_comment',
            new_name='rfi_document_comment',
        ),
    ]
