# Generated by Django 2.2.1 on 2019-08-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0003_auto_20190823_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='towerbasesubtask',
            name='no_of_casuals_atsite',
            field=models.ManyToManyField(blank=True, to='users.Casual'),
        ),
    ]
