# Generated by Django 2.2.1 on 2019-05-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190528_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btsinstallationtask',
            name='BTSinstallation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/BTSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='btsinstallationtask',
            name='BTSinstallation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/BTSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='btsinstallationtask',
            name='BTSinstallation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/BTSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='btsinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='commercialteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='electricalearthing',
            name='Earthing_connections_and_testing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='electricalearthing',
            name='Earthing_connections_and_testing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='electricalearthing',
            name='Earthing_connections_and_testing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='electricalearthing',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='electricaltasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='generatorinstallation',
            name='Generator_and_Fuel_Tank_Installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='generatorinstallation',
            name='Generator_and_Fuel_Tank_Installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='generatorinstallation',
            name='Generator_and_Fuel_Tank_Installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ElectricalEarthing/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='generatorinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='kplcsolarimage',
            name='kplc_solar_installation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/KPLCSolar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kplcsolarimage',
            name='kplc_solar_installation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/KPLCSolar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kplcsolarimage',
            name='kplc_solar_installation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/KPLCSolar/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='kplcsolarimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='mwinstallationtask',
            name='MWinstallation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/MWinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mwinstallationtask',
            name='MWinstallation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/MWinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mwinstallationtask',
            name='MWinstallation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Telecom/MWinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='mwinstallationtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='projectcosting',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='projectpurchaseorders',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='reticulationapsinstallation',
            name='Electricalreticulation_APSInstallation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ReticulationAPSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reticulationapsinstallation',
            name='Electricalreticulation_APSInstallation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ReticulationAPSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reticulationapsinstallation',
            name='Electricalreticulation_APSInstallation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/ReticulationAPSinstallation/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='reticulationapsinstallation',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='telecomtasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='undergroundtasks',
            name='Underground_ducting_and_manholes_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/UndergroundTasks/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='undergroundtasks',
            name='Underground_ducting_and_manholes_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/UndergroundTasks/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='undergroundtasks',
            name='Underground_ducting_and_manholes_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/InstallationTeam/Electrical/UndergroundTasks/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='undergroundtasks',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
    ]
