# Generated by Django 2.2.1 on 2019-06-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190610_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
