# Generated by Django 2.2.1 on 2019-05-29 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190529_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antennacoaxinstallimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='bindingimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='blockworkpanelconstimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='block_construction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlockworkPanelConstImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundFootPourImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='gate_installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.GateInstallationImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='razor_electric_fence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.RazorElectricFenceImage'),
        ),
        migrations.AlterField(
            model_name='btsandgeneatorslabsimage',
            name='concrete_pour_period',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourCuringPeriodImage'),
        ),
        migrations.AlterField(
            model_name='btsandgeneatorslabsimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ExcavationImage'),
        ),
        migrations.AlterField(
            model_name='btsandgeneatorslabsimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='cablewaysimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='concretepourcuringimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='concretepourcuringperiodimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='excavationimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='binding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BindingImage'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='concrete_pour_curing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourCuringImage'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='excavation_tower_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseImage'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='setting_site_clearing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SetSiteClearingImage'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='steel_fix_formwork',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkImage'),
        ),
        migrations.AlterField(
            model_name='foundfootpourimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='gateinstallationimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='razorelectricfenceimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='setsiteclearingimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='antenna_coax_installation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.AntennaCoaxInstallImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='cable_ways',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.CableWaysImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='tower_erection',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerErectionImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='tower_painting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerPaintImage'),
        ),
        migrations.AlterField(
            model_name='towerbaseimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='towererectionimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
        migrations.AlterField(
            model_name='towerpaintimage',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project'),
        ),
    ]
