# Generated by Django 2.2.1 on 2019-09-26 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190926_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installationteam',
            name='integration_parameter',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='integration_parameter_comment',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='rfi_document',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='rfi_document_comment',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='signoff',
        ),
        migrations.RemoveField(
            model_name='installationteam',
            name='signoff_comment',
        ),
    ]
