# Generated by Django 2.2.1 on 2019-05-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0003_auto_20190507_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='customer_user_id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='employee_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employees', to='erp_construction.Employee'),
        ),
    ]
