# Generated by Django 2.2.1 on 2019-09-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0004_auto_20190926_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='btssite',
            name='geotech_file_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='btssite',
            name='integration_parameter_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='btssite',
            name='ip_plan_comment',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/ipplans/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='btssite',
            name='rfi_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='btssite',
            name='rof_8_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='btssite',
            name='sign_off_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrof7free',
            name='free_issue_material_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrof7free',
            name='link_material_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='irrof7free',
            name='tower_complete_comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
