# Generated by Django 2.2.1 on 2019-05-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0004_auto_20190506_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=models.ImageField(upload_to='images/CivilWorksTeam/foundation/%Y/%m/%d/'),
        ),
    ]
