# Generated by Django 2.2.1 on 2019-08-26 09:49

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0004_auto_20190826_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundaryWallTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('boundary_wall_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('block_construction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlockworkPanelConstSubtask')),
                ('engineers_atsite', models.ManyToManyField(blank=True, to='users.Engineer')),
                ('foundation_foot_pouring', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundFootPourSubtask')),
                ('gate_installation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.GateInstallationSubtask')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RazorElectricFenceDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/GateInstallation/'))),
                ('casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RazorElectricFenceSubtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('razorelectricfance_image_1', models.ImageField(upload_to='images/CivilWorksTeam/RazorElectricFence/%Y/%m/%d/')),
                ('razorelectricfance_image_2', models.ImageField(upload_to='images/CivilWorksTeam/RazorElectricFence/%Y/%m/%d/')),
                ('razorelectricfance_image_3', models.ImageField(upload_to='images/CivilWorksTeam/RazorElectricFence/%Y/%m/%d/')),
                ('razorelectricfance_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='razorelectricfance_image_1',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='razorelectricfance_image_2',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='razorelectricfance_image_3',
        ),
        migrations.RemoveField(
            model_name='razorelectricfenceimage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='razorelectricfenceimage',
            name='razorelectricfance_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/GateInstallation/')),
        ),
        migrations.AlterField(
            model_name='blockworkpanelconstdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstSubtask'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BoundaryWallTask'),
        ),
        migrations.AlterField(
            model_name='foundfootpourdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourSubtask'),
        ),
        migrations.DeleteModel(
            name='BoundaryWallImage',
        ),
        migrations.AddField(
            model_name='razorelectricfencedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.RazorElectricFenceSubtask'),
        ),
        migrations.AddField(
            model_name='boundarywalltask',
            name='razor_electric_fence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.RazorElectricFenceSubtask'),
        ),
        migrations.AddField(
            model_name='razorelectricfenceimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.RazorElectricFenceDate'),
        ),
    ]
