# Generated by Django 2.2.1 on 2019-08-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0004_towerbasesubtask_no_of_casuals_atsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteblindingsubtask',
            name='binding_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/binding/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteblindingsubtask',
            name='binding_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/binding/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteblindingsubtask',
            name='binding_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/binding/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fix_formwork_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fix_formwork_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fix_formwork_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/towerbase/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/towerbase/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/towerbase/%Y/%m/%d/'),
        ),
    ]
