# Generated by Django 2.2.1 on 2019-05-22 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0004_auto_20190522_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilworksteam',
            name='bts_and_generator_slabs_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BTSAndGeneatorSlabsImage'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundationImage'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SiteWallingImage'),
        ),
    ]
