# Generated by Django 2.2.1 on 2019-08-26 10:03

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0005_auto_20190826_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockworkpanelconstdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstSubtask'),
        ),
        migrations.AlterField(
            model_name='boundarywalltask',
            name='block_construction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlockworkPanelConstSubtask'),
        ),
        migrations.AlterField(
            model_name='boundarywalltask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.FoundFootPourSubtask'),
        ),
        migrations.AlterField(
            model_name='foundfootpourdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourSubtask'),
        ),
        migrations.AlterField(
            model_name='razorelectricfencedate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/RazorElectricFence/')),
        ),
        migrations.AlterField(
            model_name='razorelectricfenceimage',
            name='razorelectricfance_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/RazorElectricFence/')),
        ),
        migrations.AlterField(
            model_name='razorelectricfencesubtask',
            name='razorelectricfance_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/RazorElectricFence/')),
        ),
        migrations.AlterField(
            model_name='razorelectricfencesubtask',
            name='razorelectricfance_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/RazorElectricFence/')),
        ),
        migrations.AlterField(
            model_name='razorelectricfencesubtask',
            name='razorelectricfance_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/RazorElectricFence/')),
        ),
    ]
