# Generated by Django 2.2.1 on 2019-08-23 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0005_auto_20190823_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteCuringPeriodSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concrete_pour_curing_period_image_1', models.ImageField(upload_to='images/CivilWorksTeam/ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('concrete_pour_curing_period_image_2', models.ImageField(upload_to='images/CivilWorksTeam/ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('concrete_pour_curing_period_image_3', models.ImageField(upload_to='images/CivilWorksTeam/ConcretePourCuringPeriod/%Y/%m/%d/')),
                ('concrete_pour_curing_period_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcretePourDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/bts/Casuals/ConcretePour/%Y/%m/%d/')),
                ('casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcretePourSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concrete_pour_curing_image_1', models.ImageField(upload_to='images/CivilWorksTeam/concretepour/%Y/%m/%d/')),
                ('concrete_pour_curing_image_2', models.ImageField(upload_to='images/CivilWorksTeam/concretepour/%Y/%m/%d/')),
                ('concrete_pour_curing_image_3', models.ImageField(upload_to='images/CivilWorksTeam/concretepour/%Y/%m/%d/')),
                ('concrete_pour_curing_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SteelFixFormworkSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('steel_fix_formwork_image_1', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/')),
                ('steel_fix_formwork_image_2', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/')),
                ('steel_fix_formwork_image_3', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/steelfix/%Y/%m/%d/')),
                ('steel_fix_formwork_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='SiteBlindingSubTask',
            new_name='BlindingSubTask',
        ),
        migrations.RemoveField(
            model_name='steelfixformworkimage',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='steelfixformworkimage',
            name='project_name',
        ),
        migrations.RenameField(
            model_name='concretepourimage',
            old_name='concrete_pour_curing_comment',
            new_name='blinding_image_comment',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='concrete_pour_curing_image_1',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='concrete_pour_curing_image_2',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='concrete_pour_curing_image_3',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='dailysteelfixformwork',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='steelfixformworkimages',
            name='project_name',
        ),
        migrations.AddField(
            model_name='concretepourimage',
            name='blinding_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/ConcretePourImage/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='steelfixformworkimages',
            name='dayly_steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.DailySteelFixFormwork'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='concrete_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubTask'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='concrete_pour_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubTask'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='excavation_tower_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseSubTask'),
        ),
        migrations.AlterField(
            model_name='foundationimage',
            name='steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubTask'),
        ),
        migrations.DeleteModel(
            name='ConcreteCuringPeriodImage',
        ),
        migrations.DeleteModel(
            name='SteelFixFormworkImage',
        ),
        migrations.AddField(
            model_name='concretepourdate',
            name='concrete_pour_subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubTask'),
        ),
        migrations.AddField(
            model_name='concretepourimage',
            name='concrete_pour_date',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourDate'),
        ),
        migrations.AddField(
            model_name='dailysteelfixformwork',
            name='steel_fix_formwork_subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubTask'),
        ),
    ]
