# Generated by Django 2.2.1 on 2019-07-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0005_auto_20190709_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='BTS_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='access_letter',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/accessletters/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_drawing',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/approveddrawings/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='geotech_file',
            field=models.FileField(blank=True, null=True, upload_to='files/Project/geotech/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='site_owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
