# Generated by Django 2.2.1 on 2019-09-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0005_auto_20190926_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='btssite',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='btssite',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
