# Generated by Django 2.2.1 on 2019-06-13 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190610_0854'),
        ('erp_construction', '0005_auto_20190613_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='users.CustomUser'),
            preserve_default=False,
        ),
    ]
