# Generated by Django 2.2.1 on 2019-08-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0006_auto_20190823_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='steelfixformworksubtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
