# Generated by Django 2.2.1 on 2019-09-27 09:19

from django.db import migrations, models
import django.db.models.deletion
import erp_construction.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0006_auto_20190926_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteCuringPeriodDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('Rebar_Concrete_Inspection', models.BooleanField(blank=True)),
                ('Concrete_Inspection_Report', models.BooleanField(blank=True)),
                ('Concrete_Cube_Test', models.ImageField(blank=True, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/ConcreteCubeTest/'))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='concrete_cube_test',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='concrete_inspection_report',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='rebar_concrete_inspection',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GenExcavationImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gen_excation_image', models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/GenExcationImages/'))),
                ('gen_excation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenConcretePourCuringPeriodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gen_concrete_pourcuring_image', models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/GenExcationCuringPeriodImages/'))),
                ('gen_concrete_pourcuring_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenCableConduitsSettingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gen_cable_conduits_setting_image', models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/GenCableConduitsImages/'))),
                ('gen_cable_conduits_setting_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryOfMaterialandEquipement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('material_and_equipement_image', models.ImageField(blank=True, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/materialandequipement/'))),
                ('material_and_equipement_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BS241Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bs241_image', models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_construction.fileshandler.filemixin.UploadToProjectDirImage('BTSProjects', 'images/CivilWorksTeam/BS241Images/'))),
                ('bs241_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concretecuringperiodimage',
            name='concrete_curing_period_docs',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcreteCuringPeriodDocs'),
            preserve_default=False,
        ),
    ]
