# Generated by Django 2.2.1 on 2019-06-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0006_issues_posted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='status',
            new_name='closed',
        ),
    ]
