# Generated by Django 2.2.1 on 2019-07-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0006_auto_20190710_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
