# Generated by Django 2.2.1 on 2019-05-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0006_auto_20190506_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundationimages',
            name='is_approved',
        ),
    ]
