# Generated by Django 2.2.1 on 2019-06-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0007_auto_20190613_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationteam',
            name='issues',
            field=models.ManyToManyField(blank=True, null=True, to='erp_construction.Issues'),
        ),
    ]
