# Generated by Django 2.2.1 on 2019-05-06 11:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0007_remove_foundationimages_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electrical_installation_image', models.ImageField(upload_to='images/InstallationTeam/Electrical/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.RenameModel(
            old_name='FoundationImages',
            new_name='FoundationImage',
        ),
        migrations.RemoveField(
            model_name='civilworksteam',
            name='access_approval',
        ),
        migrations.RemoveField(
            model_name='civilworksteam',
            name='site_walling_images',
        ),
        migrations.RemoveField(
            model_name='civilworksteam',
            name='bts_and_generator_slabs_images',
        ),
        migrations.AlterField(
            model_name='healthdocumentscivilteam',
            name='communication_plan_form',
            field=models.FileField(upload_to='files/HealthDocumentsCivilTeam/communication/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentscivilteam',
            name='incident_notification_form',
            field=models.FileField(upload_to='files/HealthDocumentsCivilTeam/incident/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentscivilteam',
            name='job_hazard_form',
            field=models.FileField(upload_to='files/HealthDocumentsCivilTeam/jobhazard/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentscivilteam',
            name='toolbox_meeting_form',
            field=models.FileField(upload_to='files/HealthDocumentsCivilTeam/toolbox/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentsinstallationteam',
            name='communication_plan_form',
            field=models.FileField(upload_to='files/HealthDocumentsInstallationTeam/communication/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentsinstallationteam',
            name='incident_notification_form',
            field=models.FileField(upload_to='files/HealthDocumentsInstallationTeam/incident/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentsinstallationteam',
            name='job_hazard_form',
            field=models.FileField(upload_to='files/HealthDocumentsInstallationTeam/jobhazard/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='healthdocumentsinstallationteam',
            name='toolbox_meeting_form',
            field=models.FileField(upload_to='files/HealthDocumentsInstallationTeam/toolbox/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='po_electrical_materials',
            field=models.FileField(upload_to='files/ProcurementTeam/poelectrical/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='po_steel',
            field=models.FileField(upload_to='files/ProcurementTeam/posteel/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='procurementteam',
            name='po_subcontractors',
            field=models.FileField(upload_to='files/ProcurementTeam/posubcontractor/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='SiteWallingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_walling_image', models.ImageField(upload_to='images/CivilWorksTeam/sitewalling/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='RFAndLinkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rf_and_link_installation_image', models.ImageField(upload_to='images/InstallationTeam/RFAndLink/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='KPLCSolarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kplc_solar_installation_image', models.ImageField(upload_to='images/InstallationTeam/KPLCSolar/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='InstallationTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_documents_comment', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True), size=None)),
                ('access_approval_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('rf_and_link_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('electrical_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('kplc_solar_installation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('electrical_installation_images', models.ManyToManyField(to='erp_construction.ElectricalImage')),
                ('health_documents', models.ManyToManyField(to='erp_construction.HealthDocumentsInstallationTeam')),
                ('kplc_solar_installation_images', models.ManyToManyField(to='erp_construction.KPLCSolarImage')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.User')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
                ('rf_and_link_installation_images', models.ManyToManyField(to='erp_construction.RFAndLinkImage')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_file', models.FileField(upload_to='files/CommercialTeam/pofile/%Y/%m/%d/')),
                ('po_file_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('initial_invoice', models.FileField(upload_to='files/CommercialTeam/initialinvoice/%Y/%m/%d/')),
                ('initial_invoice_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.User')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='BTSAndGeneatorSlabsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bts_and_generator_slabs_image', models.ImageField(upload_to='images/CivilWorksTeam/slabs/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AccessApprovalInstallation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_approval', models.FileField(upload_to='files/InstallationTeam/accessapproval/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AccessApprovalCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_approval', models.FileField(upload_to='files/CivilWorksTeam/accessapproval/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.Project')),
            ],
        ),
        migrations.AddField(
            model_name='civilworksteam',
            name='bts_and_generator_slabs_images',
            field=models.ManyToManyField(to='erp_construction.BTSAndGeneatorSlabsImage'),
        ),
    ]
