# Generated by Django 2.2.1 on 2019-08-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0007_auto_20190823_2329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DailySteelFixFormwork',
            new_name='SteelFixFormworkDate',
        ),
        migrations.RenameModel(
            old_name='SteelFixFormworkImageS',
            new_name='SteelFixFormworkImage',
        ),
    ]
