# Generated by Django 2.2.1 on 2019-08-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0008_auto_20190823_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concretepourimage',
            old_name='blinding_image_comment',
            new_name='concrete_pour_curing_comment',
        ),
        migrations.RemoveField(
            model_name='concretepourimage',
            name='blinding_image',
        ),
        migrations.AddField(
            model_name='concretepourimage',
            name='concrete_pour_curing_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/concretepour/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concretepoursubtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
