# Generated by Django 2.2.1 on 2019-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0008_auto_20190506_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilworksteam',
            name='access_approvals_field',
            field=models.ManyToManyField(to='erp_construction.AccessApprovalCivil'),
        ),
        migrations.AddField(
            model_name='installationteam',
            name='access_approvals_field',
            field=models.ManyToManyField(to='erp_construction.AccessApprovalInstallation'),
        ),
    ]
