# Generated by Django 2.2.1 on 2019-05-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0009_auto_20190506_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.ManyToManyField(to='erp_construction.SiteWallingImage'),
        ),
    ]
