# Generated by Django 2.2.1 on 2019-08-23 21:54

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0011_auto_20190824_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteclearingdate',
            name='site_clearing_subtask',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='siteclearingdates', to='erp_construction.SiteClearingSubTask'),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('BTS/Images/SiteClearingSubTask/')),
        ),
    ]
