# Generated by Django 2.2.1 on 2019-08-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0012_auto_20190824_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteCuringPeriodDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to='files/bts/Casuals/ConcretePour/%Y/%m/%d/')),
                ('casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='concretepourdate',
            old_name='concrete_pour_subtask',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='concretepourimage',
            old_name='concrete_pour_date',
            new_name='image_date',
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concretecuringperiodsubtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConcreteCuringPeriodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('concrete_curing_period_image', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/concretepour/%Y/%m/%d/')),
                ('concrete_curing_period_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('image_date', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodDate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concretecuringperioddate',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubTask'),
        ),
    ]
