# Generated by Django 2.2.1 on 2019-08-24 11:32

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0013_auto_20190824_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steelfixformworkdate',
            old_name='steel_fix_formwork_subtask',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='steelfixformworkimage',
            old_name='dayly_steel_fix_formwork',
            new_name='image_date',
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='btssite',
            name='access_letter',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('files/Project/accessletters/')),
        ),
        migrations.AlterField(
            model_name='btssite',
            name='approved_drawing',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('files/Project/approveddrawings/')),
        ),
        migrations.AlterField(
            model_name='btssite',
            name='final_acceptance_cert',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('files/SafaricomTeam/finalcert/')),
        ),
        migrations.AlterField(
            model_name='btssite',
            name='geotech_file',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('files/Project/geotech/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/siteclearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/siteclearing/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/towerbase/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/towerbase/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/towerbase/')),
        ),
    ]
