# Generated by Django 2.2.1 on 2019-08-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0014_auto_20190824_1432'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoundationImage',
            new_name='FoundationCreationTask',
        ),
        migrations.RenameField(
            model_name='foundationcreationtask',
            old_name='binding',
            new_name='blinding',
        ),
        migrations.RenameField(
            model_name='siteclearingdate',
            old_name='site_clearing_subtask',
            new_name='subtask',
        ),
        migrations.RenameField(
            model_name='siteclearingimage',
            old_name='daily_site_clearing',
            new_name='image_day',
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fixformwork_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/SteelFix/%Y/%m/%d/'),
        ),
    ]
