# Generated by Django 2.2.1 on 2019-08-24 18:17

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0016_auto_20190824_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDir('images/CivilWorksTeam/siteclearing/')),
        ),
    ]
