# Generated by Django 2.2.1 on 2019-08-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0017_auto_20190824_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteclearingdate',
            old_name='subtask',
            new_name='sub_task',
        ),
    ]
