# Generated by Django 2.2.1 on 2019-08-24 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0019_auto_20190824_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='btssite',
            old_name='project_name',
            new_name='bts_project_name',
        ),
    ]
