# Generated by Django 2.2.1 on 2019-08-25 11:50

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0020_auto_20190824_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blindingdate',
            old_name='blinding_sub_task',
            new_name='sub_task',
        ),
        migrations.RenameField(
            model_name='blindingimage',
            old_name='blinding_date',
            new_name='day_image',
        ),
        migrations.RenameField(
            model_name='siteclearingimage',
            old_name='image_day',
            new_name='day_image',
        ),
        migrations.RenameField(
            model_name='towerbasedate',
            old_name='tower_base_subtask',
            new_name='sub_task',
        ),
        migrations.AlterField(
            model_name='siteclearingdate',
            name='casuals_list',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/DateSetSiteClearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingimage',
            name='setting_site_clearing_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/dailysiteclearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/siteclearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/siteclearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingsubtask',
            name='setting_site_clearing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/siteclearing/')),
        ),
    ]
