# Generated by Django 2.2.1 on 2019-08-25 12:59

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0021_auto_20190825_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concretecuringperioddate',
            old_name='subtask',
            new_name='sub_task',
        ),
        migrations.RenameField(
            model_name='concretecuringperiodimage',
            old_name='image_date',
            new_name='day_image',
        ),
        migrations.RenameField(
            model_name='concretepourdate',
            old_name='subtask',
            new_name='sub_task',
        ),
        migrations.RenameField(
            model_name='concretepourimage',
            old_name='image_date',
            new_name='day_image',
        ),
        migrations.RenameField(
            model_name='steelfixformworkdate',
            old_name='subtask',
            new_name='sub_task',
        ),
        migrations.RenameField(
            model_name='steelfixformworkimage',
            old_name='image_date',
            new_name='day_image',
        ),
        migrations.RenameField(
            model_name='towerbaseimage',
            old_name='daily_tower_base',
            new_name='day_image',
        ),
        migrations.AlterField(
            model_name='blindingdate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/Blinding/')),
        ),
        migrations.AlterField(
            model_name='blindingimage',
            name='blinding_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/Blinding/')),
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='blindingsubtask',
            name='binding_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/binding/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('BTS/images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretepourdate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/ConcretePour/')),
        ),
        migrations.AlterField(
            model_name='concretepourimage',
            name='concrete_pour_curing_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='concretepoursubtask',
            name='concrete_pour_curing_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/concretepour/')),
        ),
        migrations.AlterField(
            model_name='siteclearingdate',
            name='casuals_list',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/SiteSiteClearing/')),
        ),
        migrations.AlterField(
            model_name='siteclearingimage',
            name='setting_site_clearing_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/siteclearing/dailysiteclearing/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworkdate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/SteelFixFormworkImage/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fixformwork_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('images/CivilWorksTeam/SteelFix/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworksubtask',
            name='steel_fix_formwork_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/steelfix/')),
        ),
        migrations.AlterField(
            model_name='towerbasedate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/TowerBase/')),
        ),
        migrations.AlterField(
            model_name='towerbaseimage',
            name='towerbase_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/towerbase/datetowerbaseimage/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/towerbase/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/towerbase/')),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='towerbase_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/towerbase/')),
        ),
    ]
