# Generated by Django 2.2.1 on 2019-08-25 13:18

from django.db import migrations, models
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0022_auto_20190825_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concretecuringperioddate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodimage',
            name='concrete_curing_period_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodsubtask',
            name='concrete_pour_curing_period_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='siteclearingimage',
            name='setting_site_clearing_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/siteclearing/')),
        ),
        migrations.AlterField(
            model_name='towerbaseimage',
            name='towerbase_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/towerbase/')),
        ),
    ]
