# Generated by Django 2.2.1 on 2019-08-25 14:01

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0023_auto_20190825_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blindingdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlindingSubTask'),
        ),
        migrations.AlterField(
            model_name='blindingimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlindingDate'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='block_construction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlockworkPanelConstImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundFootPourImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='gate_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.GateInstallationImage'),
        ),
        migrations.AlterField(
            model_name='boundarywallimage',
            name='razor_electric_fence',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.RazorElectricFenceImage'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabsimage',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodImage'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabsimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationImage'),
        ),
        migrations.AlterField(
            model_name='btssite',
            name='bts_project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BtsProject'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='bs241_and_generator_slabs_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241AndGeneatorSlabsImage'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='foundation_and_curing_images',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.FoundationCreationTask'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='site_walling_images_field',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BoundaryWallImage'),
        ),
        migrations.AlterField(
            model_name='civilworksteam',
            name='tower_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerAntennaCoaxImage'),
        ),
        migrations.AlterField(
            model_name='concretecuringperioddate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcreteCuringPeriodSubTask'),
        ),
        migrations.AlterField(
            model_name='concretecuringperiodimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcreteCuringPeriodDate'),
        ),
        migrations.AlterField(
            model_name='concretepourdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcretePourSubTask'),
        ),
        migrations.AlterField(
            model_name='concretepourimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcretePourDate'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='electrical_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ElectricalTasks'),
        ),
        migrations.AlterField(
            model_name='installationteam',
            name='telecom_tasks_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TelecomTasks'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuess', to='erp_construction.BtsSite'),
        ),
        migrations.AlterField(
            model_name='siteclearingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteclearingdates', to='erp_construction.SiteClearingSubTask'),
        ),
        migrations.AlterField(
            model_name='siteclearingimage',
            name='day_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SiteClearingDate'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkdate',
            name='casuals_list',
            field=models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/SteelFixFormwork/')),
        ),
        migrations.AlterField(
            model_name='steelfixformworkdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SteelFixFormworkSubTask'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SteelFixFormworkDate'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkimage',
            name='steel_fixformwork_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/SteelFix/')),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='antenna_coax_installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.AntennaCoaxInstallImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='cable_ways',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.CableWaysImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='tower_erection',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerErectionImage'),
        ),
        migrations.AlterField(
            model_name='towerantennacoaximage',
            name='tower_painting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerPaintImage'),
        ),
        migrations.AlterField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerBaseSubTask'),
        ),
        migrations.AlterField(
            model_name='towerbaseimage',
            name='day_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.TowerBaseDate'),
        ),
    ]
