# Generated by Django 2.2.1 on 2019-08-25 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0025_auto_20190825_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbasedates', to='erp_construction.TowerBaseSubTask'),
        ),
        migrations.AlterField(
            model_name='towerbaseimage',
            name='day_image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='towerbaseimages', to='erp_construction.TowerBaseDate'),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='towerbasesubtasks', to='erp_construction.BtsSite'),
        ),
    ]
