# Generated by Django 2.2.1 on 2019-08-25 18:25

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0026_auto_20190825_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='BS241ConcretePourCuringPeriodDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/BS241ConcretePourCuringPeriod/'))),
                ('casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BS241ConcretePourCuringPeriodImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('excavation_image', models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/'))),
                ('excavation_image_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BS241ConcretePourCuringPeriodSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('bs241_concrete_pour_curing_period_image_1', models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/'))),
                ('bs241_concrete_pour_curing_period_image_2', models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/'))),
                ('bs241_concrete_pour_curing_period_image_3', models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/'))),
                ('bs241_concrete_pour_curing_period_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcavationDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('work_day', models.DateField(blank=True, null=True)),
                ('casuals_list', models.FileField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirDate('files/Casuals/FoundFootPour/'))),
                ('casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExcavationSubTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('excavation_image_1', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/FoundFootPour/%Y/%m/%d/')),
                ('excavation_image_2', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/FoundFootPour/%Y/%m/%d/')),
                ('excavation_image_3', models.ImageField(blank=True, null=True, upload_to='images/CivilWorksTeam/FoundFootPour/%Y/%m/%d/')),
                ('excavation_comment', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_casuals_atsite', models.ManyToManyField(blank=True, to='users.Casual')),
                ('project_name', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='excavationimage',
            old_name='excavation_comment',
            new_name='excavation_image_comment',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='excavation_image_1',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='excavation_image_2',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='excavation_image_3',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='no_of_casuals_atsite',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='excavationimage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='excavationimage',
            name='excavation_image',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/FoundFootPour/')),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabsimage',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubTask'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabsimage',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubTask'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabsimage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='towerbasesubtask',
            name='project_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BtsSite'),
        ),
        migrations.DeleteModel(
            name='BS241ConcretePourCuringPeriodImage',
        ),
        migrations.AddField(
            model_name='excavationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubTask'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodimages',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationDate'),
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubTask'),
        ),
        migrations.AddField(
            model_name='excavationimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationDate'),
        ),
    ]
