# Generated by Django 2.2.1 on 2019-08-25 19:04

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0027_auto_20190825_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='BS241ConcretePourCuringPeriodImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bs241_concrete_pour_curing_period_image', models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/'))),
                ('bs241_concrete_pour_curing_period_comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='BS241AndGeneatorSlabsImage',
            new_name='BS241AndGeneratorSlabTask',
        ),
        migrations.AlterField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubTask'),
        ),
        migrations.AlterField(
            model_name='bs241concretepourcuringperiodsubtask',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excavationsubtask',
            name='excavation_image_1',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/FoundFootPour/')),
        ),
        migrations.AlterField(
            model_name='excavationsubtask',
            name='excavation_image_2',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/FoundFootPour/')),
        ),
        migrations.AlterField(
            model_name='excavationsubtask',
            name='excavation_image_3',
            field=models.ImageField(blank=True, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirSubTask('images/CivilWorksTeam/FoundFootPour/')),
        ),
        migrations.DeleteModel(
            name='BS241ConcretePourCuringPeriodImages',
        ),
        migrations.AddField(
            model_name='bs241concretepourcuringperiodimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodDate'),
        ),
    ]
