# Generated by Django 2.2.1 on 2019-08-25 19:37

from django.db import migrations, models
import django.db.models.deletion
import erp_core.fileshandler.filemixin


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('erp_construction', '0028_auto_20190825_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BS241AndGeneratorSlabTask',
            new_name='BS241AndGeneatorSlabTask',
        ),
        migrations.AlterField(
            model_name='blindingdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BlindingSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabtask',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabtask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241concretepourcuringperiodimage',
            name='bs241_concrete_pour_curing_period_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=erp_core.fileshandler.filemixin.UploadToProjectDirImage('images/CivilWorksTeam/BS241ConcretePourCuringPeriod/')),
        ),
        migrations.AlterField(
            model_name='concretecuringperioddate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='concretepourdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AlterField(
            model_name='excavationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='blinding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlindingSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='concrete_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='concrete_pour_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='excavation_tower_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='setting_site_clearing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AlterField(
            model_name='siteclearingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteclearingdates', to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AlterField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbasedates', to='erp_construction.TowerBaseSubtask'),
        ),
    ]
