# Generated by Django 2.2.1 on 2019-08-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp_construction', '0029_auto_20190825_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blindingsubtask',
            old_name='binding_comment',
            new_name='blinding_comment',
        ),
        migrations.RenameField(
            model_name='blindingsubtask',
            old_name='binding_image_1',
            new_name='blinding_image_1',
        ),
        migrations.RenameField(
            model_name='blindingsubtask',
            old_name='binding_image_2',
            new_name='blinding_image_2',
        ),
        migrations.RenameField(
            model_name='blindingsubtask',
            old_name='binding_image_3',
            new_name='blinding_image_3',
        ),
        migrations.AlterField(
            model_name='blindingdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingdates', to='erp_construction.BlindingSubtask'),
        ),
        migrations.AlterField(
            model_name='blindingimage',
            name='day_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blindingimages', to='erp_construction.BlindingDate'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabtask',
            name='bs241_concrete_pour_pouring_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241andgeneatorslabtask',
            name='foundation_foot_pouring',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AlterField(
            model_name='bs241concretepourcuringperioddate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.BS241ConcretePourCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='concretecuringperioddate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='concretepourdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AlterField(
            model_name='excavationdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erp_construction.ExcavationSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='blinding',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.BlindingSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='concrete_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcreteCuringPeriodSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='concrete_pour_curing_period',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.ConcretePourSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='excavation_tower_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.TowerBaseSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='setting_site_clearing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AlterField(
            model_name='foundationcreationtask',
            name='steel_fix_formwork',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AlterField(
            model_name='siteclearingdate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='siteclearingdates', to='erp_construction.SiteClearingSubtask'),
        ),
        migrations.AlterField(
            model_name='steelfixformworkdate',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='erp_construction.SteelFixFormworkSubtask'),
        ),
        migrations.AlterField(
            model_name='towerbasedate',
            name='sub_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='towerbasedates', to='erp_construction.TowerBaseSubtask'),
        ),
    ]
